# Generated by Django 4.2.27 on 2025-12-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0050_remove_slidingscale_tax_form_taxform"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_first_name", models.CharField(max_length=150)),
                (
                    "legal_first_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField()),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=20)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        help_text="Grade for the program year (K-12)"
                    ),
                ),
                (
                    "race_ethnicity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tshirt_size", models.CharField(max_length=20)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                ("interest_reason", models.TextField(blank=True, null=True)),
                ("hope_to_gain", models.TextField(blank=True, null=True)),
                (
                    "past_impact_student",
                    models.TextField(
                        blank=True,
                        help_text="What do you feel was your biggest impact to your team in the past?",
                        null=True,
                    ),
                ),
                (
                    "past_impact_team",
                    models.TextField(
                        blank=True,
                        help_text="What do you feel was the team's biggest impact on you?",
                        null=True,
                    ),
                ),
                ("parent1_preferred_first_name", models.CharField(max_length=150)),
                (
                    "parent1_legal_first_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("parent1_last_name", models.CharField(max_length=150)),
                ("parent1_phone_number", models.CharField(max_length=30)),
                ("parent1_email", models.EmailField(max_length=254)),
                ("parent1_email_notices", models.BooleanField(default=True)),
                (
                    "parent2_preferred_first_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent2_legal_first_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent2_last_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent2_phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "parent2_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("parent2_email_notices", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_applications",
                        to="programs.program",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apply_applications",
                        to="programs.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
