"""
Django settings for GoSAdminPortal project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json
import os
import sys
from pathlib import Path

import dj_database_url
from django.contrib.messages import constants as message_constants
from django.utils.csp import CSP

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-1oqwv49tbxn_x5f=mvb^)_r7g#l!@#*3r1sijxyvpv^424%5qd"
)

# File encryption key for EncryptedFileField, EncryptedTextField, EncryptedCharField.
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# MUST be set in production. If rotated, all encrypted data must be re-encrypted.
FILE_ENCRYPTION_KEY = os.getenv("FILE_ENCRYPTION_KEY")

# Legacy: SECRET_KEY_FALLBACKS is kept for backwards compatibility with old signed data (e.g., sessions, tokens).
# Do NOT use for file encryption. File encryption uses FILE_ENCRYPTION_KEY exclusively.
# Only include an entry when OLD_SECRET_KEY is set; otherwise Django's
# security.W021 check flags the insecure dev default. OLD_SECRET_KEY should be
# the SECRET_KEY that was in use before the most recent rotation.
_old_secret_key = os.environ.get("OLD_SECRET_KEY")
SECRET_KEY_FALLBACKS = [_old_secret_key] if _old_secret_key else []

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ["1", "true", "yes"]

# Security settings for deployment
# https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

if not DEBUG:
    from django.core.exceptions import ImproperlyConfigured

    # SECURITY: Fail fast on critical production misconfigurations
    if not os.getenv("FILE_ENCRYPTION_KEY"):
        raise ImproperlyConfigured(
            "FILE_ENCRYPTION_KEY environment variable must be set in production. "
            'Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"'
        )

    # SECURITY: SECRET_KEY must not use the insecure default in production
    default_secret = "django-insecure-1oqwv49tbxn_x5f=mvb^)_r7g#l!@#*3r1sijxyvpv^424%5qd"  # nosec B105
    if os.getenv("SECRET_KEY") == default_secret:
        raise ImproperlyConfigured(
            "SECRET_KEY is using the insecure default value. "
            "Set SECRET_KEY environment variable to a strong random string in production."
        )

    # SECURITY: ALLOWED_HOSTS must be explicitly set in production (not just localhost)
    allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "").strip()
    if not allowed_hosts_env:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS environment variable must be set in production. "
            "Set to comma-separated list of your domain(s), e.g., 'example.com,www.example.com'"
        )

    # SECURITY: Email is required for OTP login (ACCOUNT_LOGIN_BY_CODE_ENABLED=True)
    if not os.getenv("EMAIL_HOST_USER"):
        raise ImproperlyConfigured(
            "EMAIL_HOST_USER environment variable must be set in production. "
            "Required for email OTP login functionality."
        )
    if not os.getenv("EMAIL_HOST_PASSWORD"):
        raise ImproperlyConfigured(
            "EMAIL_HOST_PASSWORD environment variable must be set in production. "
            "Required for email OTP login functionality."
        )

    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in [
        "1",
        "true",
        "yes",
    ]
    SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "True").lower() in [
        "1",
        "true",
        "yes",
    ]
    CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "True").lower() in [
        "1",
        "true",
        "yes",
    ]
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", "True"
    ).lower() in ["1", "true", "yes"]
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "True").lower() in [
        "1",
        "true",
        "yes",
    ]
    SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "same-origin")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]
if os.getenv("ALLOWED_HOSTS"):
    ALLOWED_HOSTS.extend(os.getenv("ALLOWED_HOSTS").split(","))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Sites framework is required by allauth
    "django.contrib.sites",
    # Allauth apps
    "allauth",
    "allauth.account",
    # Local apps
    "django.forms",
    "programs",
    "attendance",
    "api",
    "applications",
    "portal",
    "guest_forms",
    "outreach",
    "orders",
    "badges",
    "pghistory",
    "pgtrigger",
    "audit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CSP must run early
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Throttle anonymous POSTs to the public application wizard (/apply/).
    # Placed after AuthenticationMiddleware so the 429 page can render the
    # authenticated navbar.
    "GoSAdminPortal.middleware.ApplyRateLimitMiddleware",
    "GoSAdminPortal.middleware.TimezoneMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "GoSAdminPortal.middleware.LoginRequiredMiddleware",
    "GoSAdminPortal.middleware.MentorAgreementMiddleware",
    # Must come AFTER SessionMiddleware and AuthenticationMiddleware:
    "audit.middleware.AuditHistoryMiddleware",
]

ROOT_URLCONF = "GoSAdminPortal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # CSP nonce for inline scripts
                "django.template.context_processors.csp",
                # Navbar context (current program, user role)
                "GoSAdminPortal.context_processors.navbar_context",
                # Wizard-step template defaults (e.g. `warnings`)
                "GoSAdminPortal.context_processors.wizard_context",
            ],
        },
    },
]

WSGI_APPLICATION = "GoSAdminPortal.wsgi.application"

MESSAGE_TAGS = {
    message_constants.DEBUG: "secondary",
    message_constants.INFO: "info",
    message_constants.SUCCESS: "success",
    message_constants.WARNING: "warning",
    message_constants.ERROR: "danger",
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}
if os.getenv("DATABASE_URL", None):
    db_config = dj_database_url.config(conn_max_age=600)
    db_config["CONNECTION_HEALTH_CHECKS"] = True
    if "test" in sys.argv:
        db_config["CONN_MAX_AGE"] = 0
    DATABASES["default"] = db_config

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
# Ensure project-level static assets are collected (e.g., static/samples/students_sample.csv)
STATICFILES_DIRS = [os.path.join(BASE_DIR, "programs", "static")]

# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    # Configure storage backends explicitly. Without the "default" key, Django
    # falls back to its built-in defaults (FileSystemStorage for media uploads);
    # by overriding STORAGES here we must re-include that key or any code touching
    # the default file storage raises InvalidStorageError.
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
        # and renames the files with unique names for each version to support long-term caching
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Fail tests when the code uses APIs deprecated in the current Django release,
# so deprecated usages surface in CI instead of accumulating.
TEST_RUNNER = "GoSAdminPortal.test_runner.UpgradeAwareTestRunner"

# Use project templates for form widgets
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# Django-allauth configuration
SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

LOGIN_REDIRECT_URL = "/profile/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
LOGIN_URL = "/accounts/login/"

# Email OTP Login settings
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"  # We don't need verification if we use OTP
ACCOUNT_ADAPTER = "GoSAdminPortal.adapter.AccountAdapter"
ACCOUNT_FORMS = {
    "request_login_code": "GoSAdminPortal.adapter.ProvisioningRequestLoginCodeForm",
}

# Email (SMTP) configuration via environment variables (Django 6.1+ MAILERS).
# Default to the SMTP backend; without credentials it just can't connect, which
# is fine for `manage.py check` and tests (Django's test runner swaps in the
# locmem backend). We deliberately avoid assigning a development-only backend
# (console/locmem) to MAILERS["default"] because Django 6.1's system check
# (mail.E001) rejects them when no credentials are present. For local dev that
# prints emails to the console instead, set EMAIL_BACKEND explicitly to
# django.core.mail.backends.console.EmailBackend.
# Only SMTP mailers receive transport options (host/port/credentials); other
# backends would reject them as unknown OPTIONS.
_mail_backend = os.getenv("EMAIL_BACKEND")
if not _mail_backend:
    _mail_backend = "django.core.mail.backends.smtp.EmailBackend"

_smtp_options = {
    "host": os.getenv("EMAIL_HOST", "smtp.fastmail.com"),
    "port": int(os.getenv("EMAIL_PORT", "465")),
    "username": os.getenv("EMAIL_HOST_USER", ""),
    "password": os.getenv("EMAIL_HOST_PASSWORD", ""),
    "use_tls": os.getenv("EMAIL_USE_TLS", "False").lower() in ["1", "true", "yes"],
    "use_ssl": os.getenv("EMAIL_USE_SSL", "True").lower() in ["1", "true", "yes"],
    "timeout": int(os.getenv("EMAIL_TIMEOUT", "30")),
}

MAILERS = {
    "default": {
        "BACKEND": _mail_backend,
        "OPTIONS": (
            dict(_smtp_options)
            if _mail_backend == "django.core.mail.backends.smtp.EmailBackend"
            else {}
        ),
    },
}

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "")
DEFAULT_FROM_NAME = os.getenv("DEFAULT_FROM_NAME", "Girls of Steel Admin")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# Health check throttling
# Render probes /health every few seconds; don't hit the SMTP server that often.
HEALTH_SMTP_CHECK_INTERVAL = int(os.getenv("HEALTH_SMTP_CHECK_INTERVAL", "300"))
# Shorter cooldown after a failure so recovery is detected quickly.
HEALTH_SMTP_FAILURE_COOLDOWN = int(os.getenv("HEALTH_SMTP_FAILURE_COOLDOWN", "30"))

# True while running `manage.py test`; used to silence audit logs, speed up
# password hashing, and disable rate limiting (see APPLY_RATE_LIMIT_ENABLED below).
TESTING = "test" in sys.argv

# Use fast MD5 hasher during test runs to significantly reduce test execution time.
if TESTING:
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]

# Caching. LocMemCache is fine for single-process development and tests; in
# production configure a shared backend (e.g. Redis via CACHE_BACKEND /
# CACHE_LOCATION) so rate-limit counters apply across all app servers.
CACHES = {
    "default": {
        "BACKEND": os.getenv(
            "CACHE_BACKEND", "django.core.cache.backends.locmem.LocMemCache"
        ),
        "LOCATION": os.getenv("CACHE_LOCATION", "gos-admin-portal"),
    }
}

# Public application wizard throttling (see applications/rate_limiting.py and
# GoSAdminPortal/middleware.py).
# - APPLY_IP_POST_LIMIT: max /apply/* POSTs per client IP per minute.
# - APPLY_OTP_SEND_LIMIT: max OTP codes issued per email per hour.
# - APPLY_OTP_VERIFY_LIMIT: max OTP verify attempts per application per hour.
# Disabled during the automated test run: the test client shares one IP and a
# single process-local cache, so one test's hits would otherwise leak into the
# next test's counters and cause spurious 429s.
APPLY_RATE_LIMIT_ENABLED = (
    os.getenv("APPLY_RATE_LIMIT_ENABLED", "").strip().lower()
    not in ("0", "false", "no")
    and not TESTING
)
APPLY_IP_POST_LIMIT = int(os.getenv("APPLY_IP_POST_LIMIT", "10"))
APPLY_IP_POST_WINDOW_SECONDS = int(os.getenv("APPLY_IP_POST_WINDOW_SECONDS", "60"))
APPLY_OTP_SEND_LIMIT = int(os.getenv("APPLY_OTP_SEND_LIMIT", "5"))
APPLY_OTP_VERIFY_LIMIT = int(os.getenv("APPLY_OTP_VERIFY_LIMIT", "10"))
APPLY_OTP_WINDOW_SECONDS = int(os.getenv("APPLY_OTP_WINDOW_SECONDS", "3600"))

# ── Mentor data access agreement ─────────────────────────────────────────
# Mentors (and lead mentors, and any user with is_mentor=True) must accept
# the current active MentorAgreement before accessing the portal.  Disabled
# during tests by default; force on with
# @override_settings(MENTOR_AGREEMENT_ENABLED=True).
MENTOR_AGREEMENT_ENABLED = (
    os.getenv("MENTOR_AGREEMENT_ENABLED", "").strip().lower()
    not in ("0", "false", "no")
    and not TESTING
)

# Server-side geocoding for the student map.
# Results are cached in the AddressGeocode model so each unique address is
# only looked up once.
# Configurable backends (Mapbox, Nominatim/OSM). Mapbox requires an API token.
# Example environment variables:
# GEOCODING_BACKENDS=programs.utils.geocoding.MapboxBackend,programs.utils.geocoding.NominatimBackend
# MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoibXktdXNlciIsImEiOiJjbH..."
# GEOCODING_URL=https://nominatim.openstreetmap.org/search
# GEOCODING_TIMEOUT=10
# GEOCODING_DELAY_SECONDS=1.0
GEOCODING_BACKENDS = os.getenv(
    "GEOCODING_BACKENDS",
    "programs.utils.geocoding.MapboxBackend,programs.utils.geocoding.NominatimBackend",
).split(",")
GEOCODING_URL = os.getenv("GEOCODING_URL", "https://nominatim.openstreetmap.org/search")
GEOCODING_USER_AGENT = os.getenv("GEOCODING_USER_AGENT", "GoSAdminPortal/1.0")
GEOCODING_TIMEOUT = int(os.getenv("GEOCODING_TIMEOUT", "10"))
# Nominatim asks for at most 1 request/second.
GEOCODING_DELAY_SECONDS = float(os.getenv("GEOCODING_DELAY_SECONDS", "1.0"))
MAPBOX_ACCESS_TOKEN = os.getenv("MAPBOX_ACCESS_TOKEN", "")

# Content Security Policy (Django built-in CSP)
# Allow only self by default; permit Bootstrap CDN used in base.html; images and fonts as needed
SECURE_CSP = {
    "base-uri": [CSP.SELF],
    "default-src": [CSP.SELF],
    "font-src": [CSP.SELF, "https://cdn.jsdelivr.net", "data:"],
    "frame-ancestors": [CSP.SELF],
    "img-src": [
        CSP.SELF,
        "data:",
        "*.tile.openstreetmap.org",
        "https://unpkg.com",
    ],
    "object-src": [CSP.NONE],
    "script-src": [
        CSP.SELF,
        "https://cdn.jsdelivr.net",
        "https://unpkg.com",
        CSP.NONCE,
    ],
    "style-src": [
        CSP.SELF,
        "https://cdn.jsdelivr.net",
        "https://unpkg.com",
        CSP.UNSAFE_INLINE,
    ],
}

# Multiple sender accounts for messaging UI. Each item should be a dict with keys:
# [
#   {
#       'key': 'key',
#       'display_name': 'display name for dropdown',
#       'email': 'email',
#       'username': 'username',
#       'password': ''
#   }
# ]
# Host/port/TLS/SSL come from the global EMAIL_* settings above.
# You can set via code or via an env var EMAIL_SENDER_ACCOUNTS_JSON containing a JSON list.

_email_accounts_env = os.getenv("EMAIL_SENDER_ACCOUNTS_JSON", "").strip()
EMAIL_SENDER_ACCOUNTS = []
if _email_accounts_env:
    try:
        EMAIL_SENDER_ACCOUNTS = json.loads(_email_accounts_env)
    except json.JSONDecodeError:
        # Fallback: leave empty if JSON is invalid
        EMAIL_SENDER_ACCOUNTS = []

# One MAILERS alias per sender account so the messaging UI can select a
# connection with that account's credentials via `mail.mailers["sender_<key>"]`.
# Only meaningful when the SMTP backend is in use. The account dropdown in the
# views matches on `key or email`; keep the alias scheme in sync with
# `programs/utils/notifications.get_sender_connection()`.
if _mail_backend == "django.core.mail.backends.smtp.EmailBackend":
    for _account in EMAIL_SENDER_ACCOUNTS:
        _account_key = _account.get("key") or _account.get("email")
        if not _account_key:
            continue
        _account_options = dict(_smtp_options)
        _account_options["username"] = _account.get("username") or ""
        _account_options["password"] = _account.get("password") or ""
        MAILERS[f"sender_{_account_key}"] = {
            "BACKEND": _mail_backend,
            "OPTIONS": _account_options,
        }

# Administrators who get error emails
# Provide comma-separated emails via ADMIN_EMAILS env var, e.g., "admin1@example.com,admin2@example.com"
ADMIN_EMAILS = [
    e.strip() for e in os.getenv("ADMIN_EMAILS", "").split(",") if e.strip()
]
# Django 6.0+ deprecated the (name, address) tuple format: ADMINS/MANAGERS
# must now be lists of plain email address strings.
ADMINS = ADMIN_EMAILS
MANAGERS = list(ADMINS)

# Logging configuration: verbose console + email admins on server errors when DEBUG=False
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", LOG_LEVEL)

# Silence audit console output while running unit tests so test results stay clean.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
        "simple": {
            "format": "%(levelname)s %(message)s",
        },
        "audit_json": {
            # Each audit record is already a JSON string — emit as-is.
            "format": "%(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": LOG_LEVEL,
            "formatter": "verbose",
        },
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "include_html": True,
        },
        "audit_stdout": {
            "()": "audit.logging_handlers.AuditStdoutHandler",
            "formatter": "audit_json",
        },
        "audit_stderr": {
            "()": "audit.logging_handlers.AuditStderrHandler",
            "formatter": "audit_json",
        },
        "audit_null": {
            "class": "logging.NullHandler",
        },
    },
    "loggers": {
        # Root logger: everything -> console
        "": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
        },
        # Core Django logs
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        # Server errors (HTTP 500 etc.) -> email admins and console
        "django.request": {
            "handlers": ["mail_admins", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["mail_admins", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        "cssutils": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "audit": {
            # Keep console output in development, but drop it entirely during tests.
            "handlers": ["audit_null"] if TESTING else ["audit_stdout", "audit_stderr"],
            "level": "CRITICAL" if TESTING else "INFO",
            "propagate": not TESTING,
        },
    },
}
