# Generated by Django 4.2.30 on 2026-05-07 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0055_delete_studentapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default='Welcome to the Girls of Steel application! Use this wizard to apply for one of our upcoming programs. If you started an application earlier, you can resume it below with your application ID.', help_text='Message shown on the first page of the public application wizard.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, editable=False, help_text='Public 8-character code used to resume the application.', max_length=8, unique=True)),
                ('applicant_type', models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent / Guardian'), ('mentor', 'Mentor / Volunteer')], help_text='Who is filling out this application.', max_length=16)),
                ('email', models.EmailField(blank=True, help_text='Primary email used to verify and resume the application.', max_length=254)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('email_verified', 'Email verified'), ('awaiting_parent', 'Awaiting parent'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='draft', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('otp_hash', models.CharField(blank=True, default='', max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='programs.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
