# Generated by Django 4.2.30 on 2026-05-13 00:55

import applications.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0056_programdocument'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=applications.models._application_doc_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to='applications.application')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='programs.programdocument')),
            ],
            options={
                'ordering': ['document__display_order', 'document__name'],
                'unique_together': {('application', 'document')},
            },
        ),
    ]
