# Generated by Django 4.2.30 on 2026-05-13 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationdocumentsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'permissions': [('review_application', 'Can review applications (approve / decline / edit / delete)')]},
        ),
    ]
