# Generated by Django 4.2.30 on 2026-05-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0056_programdocument'),
        ('applications', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='converted_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_applications', to='programs.student'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('email_verified', 'Email verified'), ('awaiting_parent', 'Awaiting parent'), ('submitted', 'Submitted'), ('approved', 'App Approved'), ('approved_signed', 'Approved + Signed'), ('converted', 'Converted to Student'), ('declined', 'Declined')], db_index=True, default='draft', max_length=20),
        ),
    ]
