# Generated by Django 4.2.30 on 2026-05-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_converted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='handoff_token',
            field=models.CharField(blank=True, default='', help_text='Secret token required for parent handoff access.', max_length=64),
        ),
    ]
