# Generated by Django 4.2.30 on 2026-05-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_application_handoff_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="welcome_message",
            field=models.TextField(
                default="Welcome to the Girls of Steel program application! Use this wizard to apply for one of our upcoming programs. If you started an application earlier, you can resume it below with your application ID.",
                help_text="Message shown on the first page of the public application wizard.",
            ),
        ),
    ]
