# Generated by Django 5.2.15 on 2026-06-21 03:51

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_application_application_program_status_idx_and_more"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("programs", "0078_consolidate_adult_emails"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "application_id",
                    models.CharField(
                        editable=False,
                        help_text="Public 8-character code used to resume the application.",
                        max_length=8,
                    ),
                ),
                (
                    "applicant_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "Student"),
                            ("parent", "Parent / Guardian"),
                            ("mentor", "Mentor / Volunteer"),
                        ],
                        help_text="Who is filling out this application.",
                        max_length=16,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary email used to verify and resume the application.",
                        max_length=254,
                    ),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("email_verified", "Email verified"),
                            ("awaiting_parent", "Awaiting parent"),
                            ("submitted", "Submitted"),
                            ("approved", "App Approved"),
                            ("approved_signed", "Approved + Signed"),
                            ("converted", "Converted to Student"),
                            ("declined", "Declined"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("otp_hash", models.CharField(blank=True, default="", max_length=128)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("otp_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "handoff_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Secret token required for parent handoff access.",
                        max_length=64,
                    ),
                ),
                ("decline_reason", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "applications_applicationevent" ("applicant_type", "application_id", "converted_at", "converted_student_id", "created_at", "current_step", "data", "decline_reason", "email", "email_verified_at", "handoff_token", "id", "otp_attempts", "otp_expires_at", "otp_hash", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "reviewed_at", "reviewed_by_id", "status", "submitted_at", "updated_at") VALUES (NEW."applicant_type", NEW."application_id", NEW."converted_at", NEW."converted_student_id", NEW."created_at", NEW."current_step", NEW."data", NEW."decline_reason", NEW."email", NEW."email_verified_at", NEW."handoff_token", NEW."id", NEW."otp_attempts", NEW."otp_expires_at", NEW."otp_hash", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."program_id", NEW."reviewed_at", NEW."reviewed_by_id", NEW."status", NEW."submitted_at", NEW."updated_at"); RETURN NULL;',
                    hash="84dad1084e60f37975ff2f016384242c39c45983",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_60e1b",
                    table="applications_application",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "applications_applicationevent" ("applicant_type", "application_id", "converted_at", "converted_student_id", "created_at", "current_step", "data", "decline_reason", "email", "email_verified_at", "handoff_token", "id", "otp_attempts", "otp_expires_at", "otp_hash", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "reviewed_at", "reviewed_by_id", "status", "submitted_at", "updated_at") VALUES (NEW."applicant_type", NEW."application_id", NEW."converted_at", NEW."converted_student_id", NEW."created_at", NEW."current_step", NEW."data", NEW."decline_reason", NEW."email", NEW."email_verified_at", NEW."handoff_token", NEW."id", NEW."otp_attempts", NEW."otp_expires_at", NEW."otp_hash", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."program_id", NEW."reviewed_at", NEW."reviewed_by_id", NEW."status", NEW."submitted_at", NEW."updated_at"); RETURN NULL;',
                    hash="a422fc6f4372568e3f92a4907465c96e092e84b9",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_f714e",
                    table="applications_application",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="converted_student",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.student",
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="applications.application",
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="program",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
