# Generated by Django 5.2.15 on 2026-07-02 00:56

import applications.models
import django.db.models.deletion
import programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_applicationevent_application_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent / Guardian'), ('mentor', 'Mentor / Volunteer'), ('sliding_scale', 'Sliding Scale')], help_text='Who is filling out this application.', max_length=16),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='applicant_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent / Guardian'), ('mentor', 'Mentor / Volunteer'), ('sliding_scale', 'Sliding Scale')], help_text='Who is filling out this application.', max_length=16),
        ),
        migrations.CreateModel(
            name='SlidingScaleApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('primary', 'Primary (1040 / 1040-EZ / similar)'), ('supplemental', 'Supplemental proof of income')], default='primary', max_length=16)),
                ('file', programs.models.EncryptedFileField(help_text='Encrypted proof-of-income document. Stored encrypted at rest.', upload_to=applications.models._ss_doc_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_documents', to='applications.application')),
            ],
            options={
                'ordering': ['document_type', 'uploaded_at'],
            },
        ),
    ]
