# Generated by Django 5.2.15 on 2026-07-31 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_merge_lead_mentors_into_leadmentor"),
        ("programs", "0087_remove_adult_insert_insert_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["created_at"], name="application_created_at_idx"
            ),
        ),
    ]
