# Generated by Django 5.2.16 on 2026-08-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_application_application_created_at_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="welcome_message",
            field=models.TextField(
                default="Welcome to the Girls of Steel application system! Use this wizard to apply for one of our upcoming programs or start the process of becoming a mentor.If you started an application earlier, you can resume it below with your application ID.",
                help_text="Message shown on the first page of the public application wizard.",
            ),
        ),
    ]
