# Generated by Django 5.2.15 on 2026-08-13 17:52

from django.db import migrations, models

import applications.models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_alter_sitesettings_welcome_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdocumentsubmission",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=applications.models._application_doc_upload_to
            ),
        ),
    ]
