# Generated by Django 6.1 on 2026-09-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_alter_applicationdocumentsubmission_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
