# Generated by Django 6.1 on 2026-09-15 19:34

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_delete_sitesettings"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="application",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="application",
            name="update_update",
        ),
        migrations.AddField(
            model_name="application",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this application is submitted to (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="applicationdocumentsubmission",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this submission (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_document_submissions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organization this application is submitted to (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="organizations.organization",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "applications_applicationevent" ("applicant_type", "application_id", "converted_at", "converted_student_id", "created_at", "current_step", "data", "decline_reason", "email", "email_verified_at", "handoff_token", "id", "organization_id", "otp_attempts", "otp_expires_at", "otp_hash", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "reviewed_at", "reviewed_by_id", "status", "submitted_at", "updated_at") VALUES (NEW."applicant_type", NEW."application_id", NEW."converted_at", NEW."converted_student_id", NEW."created_at", NEW."current_step", NEW."data", NEW."decline_reason", NEW."email", NEW."email_verified_at", NEW."handoff_token", NEW."id", NEW."organization_id", NEW."otp_attempts", NEW."otp_expires_at", NEW."otp_hash", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."program_id", NEW."reviewed_at", NEW."reviewed_by_id", NEW."status", NEW."submitted_at", NEW."updated_at"); RETURN NULL;',
                    hash="cea8ab67d975c28f54689b05793f154c4fb4ad6d",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_60e1b",
                    table="applications_application",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "applications_applicationevent" ("applicant_type", "application_id", "converted_at", "converted_student_id", "created_at", "current_step", "data", "decline_reason", "email", "email_verified_at", "handoff_token", "id", "organization_id", "otp_attempts", "otp_expires_at", "otp_hash", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "reviewed_at", "reviewed_by_id", "status", "submitted_at", "updated_at") VALUES (NEW."applicant_type", NEW."application_id", NEW."converted_at", NEW."converted_student_id", NEW."created_at", NEW."current_step", NEW."data", NEW."decline_reason", NEW."email", NEW."email_verified_at", NEW."handoff_token", NEW."id", NEW."organization_id", NEW."otp_attempts", NEW."otp_expires_at", NEW."otp_hash", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."program_id", NEW."reviewed_at", NEW."reviewed_by_id", NEW."status", NEW."submitted_at", NEW."updated_at"); RETURN NULL;',
                    hash="109cad5663d7e92ba973e14cfad3b11e8a0b750a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_f714e",
                    table="applications_application",
                    when="AFTER",
                ),
            ),
        ),
    ]
