# Generated by Django 6.1 on 2026-09-10 21:22

import django.db.models.deletion
from django.db import migrations, models

import travel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0116_add_travel_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Trip / event name"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("location_address", models.CharField(blank=True, max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Itinerary, packing list, chaperone plans, or anything else students/parents should know.",
                        verbose_name="Plans and details",
                    ),
                ),
                (
                    "permission_form",
                    models.FileField(
                        blank=True,
                        help_text="Optional PDF/permission slip. Parents must acknowledge it online before they can approve a signup when one is attached.",
                        upload_to=travel.models._permission_form_upload_to,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_events",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="TravelDeparture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Bus 1', '5:00 AM flight', 'leave together after practice'",
                        max_length=255,
                    ),
                ),
                ("leave_date", models.DateField()),
                ("leave_time", models.TimeField(blank=True, null=True)),
                ("meeting_location", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="travel.travelevent",
                    ),
                ),
            ],
            options={
                "ordering": ["leave_date", "leave_time", "id"],
            },
        ),
        migrations.CreateModel(
            name="TravelCostOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Hotel (2 nights)', 'Van ride', 'Flight'",
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit_label",
                    models.CharField(
                        default="per person",
                        help_text="e.g. 'per person', 'total', 'per night' (informational)",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_options",
                        to="travel.travelevent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TravelMentorSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_driver",
                    models.BooleanField(
                        default=False,
                        help_text="Check for mentors who are driving. Set by Lead Mentors.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adult",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_mentor_signups",
                        to="programs.adult",
                        verbose_name="Mentor",
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentor_signups",
                        to="travel.traveldeparture",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_signups",
                        to="travel.travelevent",
                    ),
                ),
            ],
            options={
                "unique_together": {("adult", "event")},
            },
        ),
        migrations.CreateModel(
            name="TravelSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested (awaiting parent approval)"),
                            ("approved", "Approved"),
                            ("declined", "Declined by parent"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="interested",
                        max_length=20,
                    ),
                ),
                (
                    "approved_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Snapshot of the cost the parent approved.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("permission_acknowledged", models.BooleanField(default=False)),
                (
                    "permission_acknowledged_by",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Permission form acknowledged by",
                    ),
                ),
                (
                    "permission_acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_travel_signups",
                        to="programs.adult",
                        verbose_name="Approving parent",
                    ),
                ),
                (
                    "cost_items",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The cost check-list items that apply to this student.",
                        related_name="signups",
                        to="travel.travelcostoption",
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signups",
                        to="travel.traveldeparture",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="travel.travelevent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_signups",
                        to="programs.student",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("student", "event")},
            },
        ),
    ]
