# Generated by Django 6.1 on 2026-09-10 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0116_add_travel_feature"),
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelParentChaperoneSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adult",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_parent_chaperone_signups",
                        to="programs.adult",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which departure this parent plans to travel with (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_chaperone_signups",
                        to="travel.traveldeparture",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_chaperones",
                        to="travel.travelevent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("adult", "event")},
            },
        ),
    ]
