# Generated by Django 5.2.15 on 2026-08-07 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import guest_forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0089_rolepermission_mentor_attendance_write"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[("student", "Student"), ("adult", "Adult")],
                        help_text="Whether this form is for students or adults.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name shown to guests (e.g. 'Photo Release Form').",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional longer explanation shown next to the download link.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The blank PDF (or other file) for the guest to download, fill out, and re-upload.",
                        upload_to=guest_forms.models._guest_form_upload_to,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If checked, guests must upload a signed copy.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this form from guests without deleting it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_forms",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GuestFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_first_name", models.CharField(blank=True, max_length=150)),
                ("student_last_name", models.CharField(blank=True, max_length=150)),
                ("parent_first_name", models.CharField(blank=True, max_length=150)),
                ("parent_last_name", models.CharField(blank=True, max_length=150)),
                ("team_number", models.CharField(blank=True, max_length=20)),
                ("adult_first_name", models.CharField(blank=True, max_length=150)),
                ("adult_last_name", models.CharField(blank=True, max_length=150)),
                ("adult_team_number", models.CharField(blank=True, max_length=20)),
                (
                    "file",
                    models.FileField(
                        help_text="The signed form uploaded by the guest.",
                        upload_to=guest_forms.models._guest_submission_upload_to,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, default="")),
                (
                    "guest_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="guest_forms.guestform",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_guest_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
