# Generated by Django 5.2.15 on 2026-08-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guest_forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestform",
            options={
                "ordering": ["program", "display_order", "name"],
                "permissions": [
                    (
                        "review_guestform",
                        "Can review guest form submissions (approve / decline)",
                    )
                ],
            },
        ),
    ]
