# Generated by Django 5.2.15 on 2026-08-08 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_forms", "0003_assign_leadmentor_permission"),
        ("programs", "0089_rolepermission_mentor_attendance_write"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestform",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_forms",
                to="programs.program",
            ),
        ),
    ]
