# Generated by Django 5.2.15 on 2026-08-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_forms", "0004_alter_guestform_program"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestform",
            options={
                "ordering": ["display_order", "name"],
                "permissions": [
                    (
                        "review_guestform",
                        "Can review guest form submissions (approve / decline)",
                    )
                ],
            },
        ),
        migrations.RemoveField(
            model_name="guestform",
            name="program",
        ),
        migrations.AddField(
            model_name="guestform",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier for direct links (e.g. 'photo-release').",
                max_length=100,
                unique=True,
            ),
        ),
    ]
