# Generated by Django 5.2.15 on 2026-08-08 04:47

from django.db import migrations, models

import programs.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "guest_forms",
            "0005_alter_guestform_options_remove_guestform_program_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestform",
            options={
                "ordering": ["display_order", "name"],
                "permissions": [
                    ("review_guestform", "Can review guest form submissions")
                ],
            },
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="adult_first_name",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="adult_last_name",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="adult_team_number",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="parent_first_name",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="parent_last_name",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="review_notes",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="student_first_name",
        ),
        migrations.RemoveField(
            model_name="guestformsubmission",
            name="student_last_name",
        ),
        migrations.AddField(
            model_name="guestform",
            name="legal_notices_url",
            field=models.URLField(
                default="https://www.cmu.edu/legal/",
                help_text="URL for CMU legal notices agreement.",
            ),
        ),
        migrations.AddField(
            model_name="guestform",
            name="safety_guidelines_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL for Practice Field Safety and Use Guidelines.",
            ),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="agreed_legal_notices",
            field=models.BooleanField(
                default=False,
                help_text="I have read and reviewed the notices at CMU Legal.",
            ),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="agreed_safety_guidelines",
            field=models.BooleanField(
                default=False,
                help_text="I have read and reviewed the Practice Field Safety and Use Guidelines.",
            ),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="emergency_contact_other",
            field=models.CharField(
                blank=True, help_text="Specify if 'Other' relationship.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                validators=[programs.validators.validate_phone_number],
            ),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="emergency_contact_relationship",
            field=models.CharField(
                choices=[
                    ("parent_guardian", "Parent/Guardian"),
                    ("spouse_partner", "Spouse/Partner"),
                    ("other", "Other"),
                ],
                default="parent_guardian",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="participant_first_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="participant_last_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Participant or parent/guardian phone number.",
                max_length=30,
                validators=[programs.validators.validate_phone_number],
            ),
        ),
        migrations.AddField(
            model_name="guestformsubmission",
            name="phone_type",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("cell", "Cell"),
                    ("work", "Work"),
                    ("other", "Other"),
                ],
                default="cell",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="guestformsubmission",
            name="team_number",
            field=models.CharField(
                blank=True, help_text="Team number (e.g., FRC 3504).", max_length=20
            ),
        ),
    ]
