# Generated by Django 5.2.16 on 2026-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_forms", "0006_alter_guestform_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestform",
            name="safety_guidelines_url",
            field=models.URLField(
                blank=True,
                default="https://docs.google.com/document/d/1xG734QEL2fZbzQ8PxABA5uzUwf5XEt52H3aUGPN6-1c/edit?tab=t.0",
                help_text="URL for Practice Field Safety and Use Guidelines.",
            ),
        ),
    ]
