# Generated by Django 5.2.15 on 2026-08-13 17:52

from django.db import migrations, models

import guest_forms.models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_forms", "0008_grant_review_guestform_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestform",
            name="file",
            field=models.FileField(
                help_text="The blank PDF (or other file) for the guest to download, fill out, and re-upload.",
                max_length=255,
                upload_to=guest_forms.models._guest_form_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="guestformsubmission",
            name="file",
            field=models.FileField(
                help_text="The signed form uploaded by the guest.",
                max_length=255,
                upload_to=guest_forms.models._guest_submission_upload_to,
            ),
        ),
    ]
