# Generated by Django 5.2.15 on 2026-07-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('attendance', '0005_remove_kioskconfig_api_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiClientKey',
        ),
    ]
