# Generated by Django 6.1 on 2026-09-11 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0117_alter_rolepermission_section"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#0d6efd",
                        help_text="CSS hex color for calendar display (e.g. #0d6efd)",
                        max_length=7,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("anonymous", "Public (no login required)"),
                            ("members", "Members (logged-in users)"),
                            ("invite_only", "Invite Only (ACL-controlled)"),
                        ],
                        default="members",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manually managed"),
                            ("outreach", "Outreach events (auto-synced)"),
                            ("travel", "Travel events (auto-synced)"),
                            ("program_hours", "Program hours (auto-synced)"),
                            ("custom", "Custom source"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Program scope. Leave blank for org-wide feeds.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_feeds",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=500)),
                (
                    "rrule_ical",
                    models.TextField(
                        blank=True,
                        help_text="iCalendar RRULE string for recurring events (e.g. FREQ=WEEKLY;BYDAY=TU). Leave blank for one-time events.",
                    ),
                ),
                (
                    "exdate_ical",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of excluded dates for recurring events (YYYY-MM-DD format).",
                    ),
                ),
                ("uid", models.CharField(editable=False, max_length=255, unique=True)),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="Primary key of the source record (e.g. OutreachShift pk) for auto-synced events.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="calendar_feeds.calendarfeed",
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime", "title"],
            },
        ),
        migrations.CreateModel(
            name="CalendarFeedACL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Mentor", "Mentor"),
                            ("Parent", "Parent"),
                            ("Student", "Student"),
                            ("Alumni", "Alumni"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_read", models.BooleanField(default=True)),
                ("can_write", models.BooleanField(default=False)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acls",
                        to="calendar_feeds.calendarfeed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Feed ACL",
                "verbose_name_plural": "Calendar Feed ACLs",
                "unique_together": {("feed", "role")},
            },
        ),
        migrations.CreateModel(
            name="EventException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_date",
                    models.DateField(
                        help_text="The original date of the recurring event instance being modified."
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("moved", "Moved to different date/time"),
                            ("deleted", "Deleted (skip this instance)"),
                            ("changed", "Details changed (title/location/etc)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("new_start_datetime", models.DateTimeField(blank=True, null=True)),
                ("new_end_datetime", models.DateTimeField(blank=True, null=True)),
                ("new_title", models.CharField(blank=True, max_length=300)),
                ("new_location", models.CharField(blank=True, max_length=500)),
                ("new_description", models.TextField(blank=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Internal note about why this exception was made.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="calendar_feeds.calendarevent",
                    ),
                ),
            ],
            options={
                "ordering": ["original_date"],
                "unique_together": {("event", "original_date")},
            },
        ),
    ]
