# Generated by Django 5.2.16 on 2026-08-21 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0001_initial"),
        ("programs", "0104_school_district"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outreachevent",
            options={"ordering": ["start_date", "start_time"]},
        ),
        migrations.AddField(
            model_name="outreachevent",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outreach_events",
                to="programs.program",
            ),
        ),
    ]
