# Generated by Django 5.2.15 on 2026-08-22 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0008_finalize_signup_shift"),
        ("programs", "0106_remove_student_insert_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachMentorSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adult",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_mentor_signups",
                        to="programs.adult",
                        verbose_name="Mentor",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_signups",
                        to="outreach.outreachshift",
                    ),
                ),
            ],
            options={
                "unique_together": {("adult", "shift")},
            },
        ),
    ]
