# Generated by Django 6.1 on 2026-08-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0009_outreachmentorsignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="outreachsignup",
            name="checked_in_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this student actually arrived (recorded at the event).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="outreachsignup",
            name="checked_out_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this student actually left (recorded at the event).",
                null=True,
            ),
        ),
    ]
