# Generated by Django 6.1 on 2026-09-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0011_backfill_outreach_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "address"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "address"), name="unique_outreach_location"
                    )
                ],
            },
        ),
    ]
