# Generated by Django 6.1 on 2026-09-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("outreach", "0012_outreachlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="outreachevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this event (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outreach_events",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="outreachlocation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this saved location (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outreach_locations",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="outreachmentorsignup",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this mentor signup (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outreach_mentor_signups",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="outreachshift",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this shift (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outreach_shifts",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="outreachsignup",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this signup (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outreach_signups",
                to="organizations.organization",
            ),
        ),
    ]
