# Generated by Django 6.1 on 2026-09-19 05:12

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0014_backfill_organization_gos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outreachmentorsignup",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("adult__preferred_first_name"),
                            models.F("adult__legal_first_name"),
                        )
                    ),
                    django.db.models.functions.text.Lower("adult__last_name"),
                    "adult__pk",
                ]
            },
        ),
    ]
