# Generated by Django 5.2.15 on 2026-06-21 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ADMISSION_DECISION", "Admission decision made"),
                            ("CONTACT_INFO_UPDATED", "Contact/address info updated"),
                            ("GUARDIAN_ADDED", "Guardian/parent added to student"),
                            (
                                "GUARDIAN_REMOVED",
                                "Guardian/parent removed from student",
                            ),
                            ("ENROLLMENT_CHANGED", "Enrollment status changed"),
                            ("ACCOUNT_CREATED", "User account created"),
                            ("ACCOUNT_DEACTIVATED", "User account deactivated"),
                            ("ROLE_CHANGED", "User role changed"),
                            ("PASSWORD_RESET", "Password reset by admin"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Model name of the affected resource, e.g. 'Student', 'User'.",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        db_index=True,
                        help_text="PK of the affected record (stored as string to support UUIDs).",
                        max_length=255,
                    ),
                ),
                (
                    "resource_repr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable label of the resource at the time of the event.",
                        max_length=255,
                    ),
                ),
                (
                    "before",
                    models.JSONField(
                        blank=True,
                        help_text="Field values before the change. NULL for creation events.",
                        null=True,
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True,
                        help_text="Field values after the change. NULL for deletion events.",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address that triggered the action.",
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Django session key at the time of the action.",
                        max_length=255,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        db_index=True,
                        default="success",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action (by PK). NULL = system or anonymous.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_resource_idx",
                    ),
                    models.Index(
                        fields=["actor", "timestamp"], name="audit_actor_ts_idx"
                    ),
                    models.Index(
                        fields=["event", "timestamp"], name="audit_event_ts_idx"
                    ),
                ],
            },
        ),
    ]
