# Generated by hand for adding Parent model
from django.db import migrations, models


RELATIONSHIP_CHOICES = [
    ('parent', 'Parent'),
    ('mother', 'Mother'),
    ('father', 'Father'),
    ('grandparent', 'Grandparent'),
    ('grandmother', 'Grandmother'),
    ('grandfather', 'Grandfather'),
    ('pibling', 'Pibling'),
    ('aunt', 'Aunt'),
    ('uncle', 'Uncle'),
    ('sibling', 'Sibling'),
    ('sister', 'Sister'),
    ('brother', 'Brother'),
    ('friend', 'Friend'),
    ('guardian', 'Guardian'),
    ('other', 'Other'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_school_student_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('preferred_first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('relationship_to_student', models.CharField(choices=RELATIONSHIP_CHOICES, default='parent', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='parents', to='programs.student'),
        ),
    ]
