# Generated by Django 4.2.24 on 2025-09-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0007_mentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
