# Generated by Django 4.2.24 on 2025-09-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_slidingscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='camp_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_via',
            field=models.CharField(choices=[('check', 'Check'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('camp', 'Camp'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
