# Generated by Django 4.2.24 on 2025-09-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_mentor_photo_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidingscale',
            name='adjusted_gross_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slidingscale',
            name='family_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slidingscale',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
