# Generated by Django 4.2.24 on 2025-09-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0014_slidingscale_adjusted_gross_income_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slidingscale",
            old_name="amount",
            new_name="percent",
        ),
        migrations.AlterField(
            model_name="slidingscale",
            name="percent",
            field=models.DecimalField(
                max_digits=5,
                decimal_places=2,
                help_text="Percent discount applied to total program fees (0–100).",
            ),
        ),
    ]
