# Generated by Django 4.2.24 on 2025-09-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0016_fee_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["first_name", "last_name"]},
        ),
    ]
