# Generated by Django 4.2.24 on 2025-09-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0019_feeassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feeassignment",
            name="amount_override",
        ),
        migrations.RemoveField(
            model_name="feeassignment",
            name="waived",
        ),
    ]
