# Generated by Django 4.2.24 on 2025-09-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0021_rename_student_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="legal_first_name",
            field=models.CharField(max_length=150, verbose_name="Legal first name"),
        ),
    ]
