# Generated by Django 4.2.24 on 2025-09-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0028_school_address_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
