# Generated by Junie to set Parent.email_updates default to False
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0031_parent_email_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="email_updates",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this parent/guardian will receive email updates.",
            ),
        ),
    ]
