# Generated by Django 4.2.27 on 2025-12-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0048_alter_rolepermission_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slidingscale",
            name="tax_form",
            field=models.FileField(
                blank=True,
                help_text="Uploaded tax form for sliding scale verification. Will be deleted after review.",
                null=True,
                upload_to="tax_forms/",
            ),
        ),
    ]
