# Generated by Django 4.2.27 on 2025-12-24 03:32

import django.db.models.deletion
from django.db import migrations, models

import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0049_slidingscale_tax_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slidingscale",
            name="tax_form",
        ),
        migrations.CreateModel(
            name="TaxForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    programs.models.EncryptedFileField(
                        help_text="Uploaded tax form for sliding scale verification. Will be deleted after review.",
                        upload_to="tax_forms/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sliding_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_forms",
                        to="programs.slidingscale",
                    ),
                ),
            ],
        ),
    ]
