# Generated by Django 4.2.27 on 2026-01-06 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0050_remove_slidingscale_tax_form_taxform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("FRC", "FRC"),
                            ("FTC", "FTC"),
                            ("FLL_CHALLENGE", "FLL Challenge"),
                            ("FLL_EXPLORE", "FLL Explore"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "color",
                    models.CharField(
                        default="#0000ff",
                        help_text="Hex color code (e.g. #0000ff)",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "ordering": ["team_type", "number"],
                "unique_together": {("team_type", "number")},
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="programs.team",
            ),
        ),
    ]
