# Generated by Django 4.2.27 on 2025-12-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0050_remove_slidingscale_tax_form_taxform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_parent", "Pending Parent"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentapplication",
            unique_together={
                ("program", "legal_first_name", "last_name", "parent_email")
            },
        ),
    ]
