# Generated by Django 4.2.27 on 2026-01-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0051_team_enrollment_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
