# Generated by Django 4.2.27 on 2026-01-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0052_team_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#0000ff",
                        help_text="Hex color code (e.g. #0000ff)",
                        max_length=7,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crews",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "program")},
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="crew",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="programs.crew",
            ),
        ),
    ]
