# Generated by Django 4.2.29 on 2026-04-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0053_crew_enrollment_crew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slidingscale",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Effective date the sliding scale starts. Only fees on or after this date will be discounted.",
                null=True,
            ),
        ),
    ]
