# Generated by Django 4.2.30 on 2026-04-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0054_alter_slidingscale_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_code",
                    models.CharField(db_index=True, max_length=8, unique=True),
                ),
                ("email_to_verify", models.EmailField(max_length=254)),
                ("otp_code", models.CharField(blank=True, max_length=6, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("student_parent", "Student/Parent"),
                            ("mentor_volunteer", "Mentor/Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_handoff", "Pending Parent Completion"),
                            ("pending_approval", "Pending Lead Mentor Approval"),
                            ("pending_disclosures", "Pending Disclosures"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("current_step", models.CharField(default="identity", max_length=50)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "existing_primary_adult",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_apps",
                        to="programs.adult",
                    ),
                ),
                (
                    "existing_secondary_adult",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_apps",
                        to="programs.adult",
                    ),
                ),
                (
                    "existing_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="programs.student",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_applications",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationFieldConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Internal name of the field",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Friendly label for the field", max_length=200
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_required", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DisclosureForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("pdf_file", models.FileField(upload_to="disclosures/templates/")),
                (
                    "required_for_role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("parent", "Parent"),
                            ("mentor", "Mentor/Volunteer"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationDisclosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signed_pdf_upload",
                    models.FileField(upload_to="disclosures/signed/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disclosures",
                        to="programs.application",
                    ),
                ),
                (
                    "disclosure_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.disclosureform",
                    ),
                ),
            ],
        ),
    ]
