# Generated by Django 4.2.30 on 2026-05-07 01:53
#
# Manually adjusted: the StudentApplication table may or may not exist in
# any given environment (some local DBs predate it ever being created).
# We always remove the model from Django's migration state, but only drop
# the underlying table if it actually exists in the database.

from django.db import migrations


def drop_table_if_exists(apps, schema_editor):
    table_name = "programs_studentapplication"
    connection = schema_editor.connection
    existing = connection.introspection.table_names()
    if table_name in existing:
        with connection.cursor() as cursor:
            cursor.execute(
                schema_editor.sql_delete_table % {
                    "table": connection.ops.quote_name(table_name),
                }
            )


def noop_reverse(apps, schema_editor):
    # Reversing this migration is not supported; the model definition
    # has been removed from the codebase.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0054_alter_slidingscale_date'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='StudentApplication',
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_table_if_exists, noop_reverse),
            ],
        ),
    ]
