# Generated by Django 4.2.30 on 2026-04-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0055_application_applicationfieldconfig_disclosureform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_parent_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="parent_email_to_verify",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="parent_otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
