# Generated by Django 4.2.30 on 2026-05-13 00:55

import django.db.models.deletion
from django.db import migrations, models

import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0055_delete_studentapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name shown to applicants (e.g. 'Photo release form').",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional longer explanation shown next to the download link.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The blank PDF (or other file) for the applicant to download and fill out.",
                        upload_to=programs.models._program_document_upload_to,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If checked, applicants must upload a signed copy before being marked complete.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this document from applicants without deleting it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "display_order", "name"],
            },
        ),
    ]
