# Generated by Django 4.2.30 on 2026-05-23 00:03

from django.db import migrations, models

import programs.validators


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0058_alter_student_tshirt_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="directory_consent",
            field=models.BooleanField(
                default=True,
                verbose_name="OK to share name, address, and phone for student directory",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="cell_phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[programs.validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[programs.validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="home_phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[programs.validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[programs.validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="cell_phone_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[programs.validators.validate_phone_number],
            ),
        ),
    ]
