# Generated by Django 4.2.30 on 2026-05-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "programs",
            "0063_adult_specific_relationship_alter_adult_relationship_to_student",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YXS", "Youth XS"),
                    ("YS", "Youth S"),
                    ("YM", "Youth M"),
                    ("YL", "Youth L"),
                    ("YXL", "Youth XL"),
                    ("XS", "Adult XS"),
                    ("S", "Adult S"),
                    ("M", "Adult M"),
                    ("L", "Adult L"),
                    ("XL", "Adult XL"),
                    ("2XL", "Adult 2XL"),
                    ("3XL", "Adult 3XL"),
                    ("4XL", "Adult 4XL"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
