# Generated by Django 5.1.15 on 2026-05-27 01:29

from django.db import migrations, models

import programs.models
import programs.validators


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0068_alter_adult_state_alter_school_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adult",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[programs.validators.validate_zip_code],
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[programs.validators.validate_zip_code],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="allergies",
            field=programs.models.EncryptedTextField(
                blank=True,
                help_text="List any food, drug, environmental, or other allergies. Include severity and typical reactions if known.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="dietary_restrictions",
            field=programs.models.EncryptedTextField(
                blank=True,
                help_text="Dietary needs or restrictions (e.g., vegetarian, halal, no pork, no nuts).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="medical_notes",
            field=programs.models.EncryptedTextField(
                blank=True,
                help_text="Other health information staff should know (e.g., asthma, seizures, physical limitations).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[programs.validators.validate_zip_code],
            ),
        ),
    ]
