# Generated by Django 5.1.15 on 2026-05-30 16:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0070_add_tshirt_size_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="cost",
            field=models.CharField(
                blank=True,
                help_text="Program cost (e.g., $300 or $200-500).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.date(1900, 1, 1),
                help_text="Student's date of birth. The default value (1900-01-01) is a placeholder — please enter the actual date.",
            ),
        ),
    ]
