# Generated by Django 5.1.15 on 2026-05-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0071_program_cost_alter_student_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="year",
        ),
    ]
