# Generated by Django 5.1.15 on 2026-05-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0072_remove_program_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="fee",
        ),
    ]
