# Generated by Django 5.1.15 on 2026-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0073_remove_payment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='grade_range_end',
            field=models.IntegerField(blank=True, help_text='Ending grade for this program (12 for 12th grade).', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='grade_range_start',
            field=models.IntegerField(blank=True, help_text='Starting grade for this program (0 for K).', null=True),
        ),
    ]
