# Generated by Django 5.1.15 on 2026-06-02 04:26

import django.db.models.deletion
from django.db import migrations, models



def cleanup_duplicate_emails(apps, schema_editor):
    Adult = apps.get_model("programs", "Adult")
    emails_seen = set()
    for adult in Adult.objects.exclude(email__isnull=True).exclude(email="").order_by("id"):
        if adult.email in emails_seen:
            adult.email = None
            adult.save()
        else:
            emails_seen.add(adult.email)


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0074_program_grade_range_end_program_grade_range_start"),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_emails),
        migrations.RemoveField(
            model_name="adult",
            name="relationship_to_student",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="specific_relationship",
        ),
        migrations.AlterField(
            model_name="adult",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="directory_consent",
            field=models.BooleanField(
                default=True,
                verbose_name="OK to share name, address, email, and phone for student directory",
            ),
        ),
        migrations.CreateModel(
            name="AdultStudentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_to_student",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("grandparent", "Grandparent"),
                            ("pibling", "Pibling (aunt/uncle)"),
                            ("sibling", "Sibling"),
                            ("guardian", "Guardian"),
                            ("family_friend", "Family Friend"),
                            ("other", "Other"),
                        ],
                        default="parent",
                        max_length=20,
                    ),
                ),
                (
                    "specific_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Specific relationship, e.g. father, stepmom, foster parent, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "adult",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="programs.adult"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("adult", "student")},
            },
        ),
        migrations.RemoveField(
            model_name="adult",
            name="students",
        ),
        migrations.AddField(
            model_name="adult",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="adults",
                through="programs.AdultStudentRelationship",
                to="programs.student",
            ),
        ),
    ]
