# Generated by Django 5.2.15 on 2026-06-21 03:51

import datetime

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import programs.models
import programs.validators


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("programs", "0078_consolidate_adult_emails"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdultEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "is_parent",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this adult is a parent/guardian of any student.",
                    ),
                ),
                (
                    "is_mentor",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this adult serves as a mentor/volunteer.",
                    ),
                ),
                (
                    "is_alumni",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this adult is a program alumni.",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                (
                    "preferred_first_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("pronouns", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email (e.g. Gmail). Used for login and notifications.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[programs.validators.validate_phone_number],
                    ),
                ),
                (
                    "cell_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[programs.validators.validate_phone_number],
                    ),
                ),
                (
                    "home_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[programs.validators.validate_phone_number],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        default="PA",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[programs.validators.validate_zip_code],
                    ),
                ),
                ("start_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("mentor", "Mentor"),
                            ("volunteer", "Volunteer"),
                            ("chaperone", "Chaperone"),
                        ],
                        default="mentor",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/adults/"
                    ),
                ),
                (
                    "andrew_id",
                    models.CharField(
                        blank=True,
                        help_text="CMU Andrew ID. Assigned by lead mentors; only applies to mentors/CMU staff.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "andrew_email",
                    models.EmailField(
                        blank=True,
                        help_text="CMU Andrew email (andrew_id@andrew.cmu.edu). Assigned by lead mentors.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "andrew_id_expiration",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date of this Andrew ID.",
                        null=True,
                    ),
                ),
                ("on_discord", models.BooleanField(default=False)),
                (
                    "discord_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("has_cmu_id_card", models.BooleanField(default=False)),
                ("has_cmu_building_access", models.BooleanField(default=False)),
                ("has_google_team_drive_access", models.BooleanField(default=False)),
                ("has_google_mentor_drive_access", models.BooleanField(default=False)),
                ("has_google_admin_drive_access", models.BooleanField(default=False)),
                ("on_first_website", models.BooleanField(default=False)),
                ("signed_first_consent_form", models.BooleanField(default=False)),
                ("on_canvas", models.BooleanField(default=False)),
                ("has_zoom_account", models.BooleanField(default=False)),
                ("in_onshape_classroom", models.BooleanField(default=False)),
                ("on_canva", models.BooleanField(default=False)),
                ("on_google_mentor_group", models.BooleanField(default=False)),
                ("on_google_field_crew_group", models.BooleanField(default=False)),
                ("has_paca_clearance", models.BooleanField(default=False)),
                ("has_patch_clearance", models.BooleanField(default=False)),
                ("has_fbi_clearance", models.BooleanField(default=False)),
                (
                    "pa_clearances_expiration_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[programs.validators.validate_phone_number],
                    ),
                ),
                (
                    "email_updates",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this adult will receive email updates.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("college", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("employer", models.CharField(blank=True, max_length=200, null=True)),
                ("job_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ok_to_contact",
                    models.BooleanField(
                        default=True,
                        help_text="Consents to be contacted about news/opportunities",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdultStudentRelationshipEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "relationship_to_student",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("grandparent", "Grandparent"),
                            ("pibling", "Pibling (aunt/uncle)"),
                            ("sibling", "Sibling"),
                            ("guardian", "Guardian"),
                            ("family_friend", "Family Friend"),
                            ("other", "Other"),
                        ],
                        default="parent",
                        max_length=20,
                    ),
                ),
                (
                    "specific_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Specific relationship, e.g. father, stepmom, foster parent, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnrollmentEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "legal_first_name",
                    models.CharField(max_length=150, verbose_name="Legal first name"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="First name"
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("pronouns", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "date_of_birth",
                    models.DateField(
                        default=datetime.date(1900, 1, 1),
                        help_text="Student's date of birth. The default value (1900-01-01) is a placeholder — please enter the actual date.",
                    ),
                ),
                (
                    "has_passed_clearances",
                    models.BooleanField(
                        default=False,
                        help_text="Check if the student has completed and passed required background clearances.",
                    ),
                ),
                (
                    "clearances_expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date for the student's background clearances (if applicable).",
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/students/"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        default="PA",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[programs.validators.validate_zip_code],
                    ),
                ),
                (
                    "cell_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        validators=[programs.validators.validate_phone_number],
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "directory_consent",
                    models.BooleanField(
                        default=True,
                        verbose_name="OK to share name, address, email, and phone for student directory",
                    ),
                ),
                ("andrew_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "andrew_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Expected high school graduation year",
                        null=True,
                    ),
                ),
                (
                    "tshirt_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YXS", "Youth XS"),
                            ("YS", "Youth S"),
                            ("YM", "Youth M"),
                            ("YL", "Youth L"),
                            ("YXL", "Youth XL"),
                            ("XS", "Adult XS"),
                            ("S", "Adult S"),
                            ("M", "Adult M"),
                            ("L", "Adult L"),
                            ("XL", "Adult XL"),
                            ("2XL", "Adult 2XL"),
                            ("3XL", "Adult 3XL"),
                            ("4XL", "Adult 4XL"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("seen_once", models.BooleanField(default=False)),
                ("on_discord", models.BooleanField(default=False)),
                (
                    "discord_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "allergies",
                    programs.models.EncryptedTextField(
                        blank=True,
                        help_text="List any food, drug, environmental, or other allergies. Include severity and typical reactions if known.",
                        null=True,
                    ),
                ),
                (
                    "dietary_restrictions",
                    programs.models.EncryptedTextField(
                        blank=True,
                        help_text="Dietary needs or restrictions (e.g., vegetarian, halal, no pork, no nuts).",
                        null=True,
                    ),
                ),
                (
                    "medical_notes",
                    programs.models.EncryptedTextField(
                        blank=True,
                        help_text="Other health information staff should know (e.g., asthma, seizures, physical limitations).",
                        null=True,
                    ),
                ),
                (
                    "first_has_account",
                    models.BooleanField(
                        default=False, verbose_name="Has FIRST account"
                    ),
                ),
                (
                    "first_attached_to_parent_account",
                    models.BooleanField(
                        default=False, verbose_name="Attached to parent account"
                    ),
                ),
                (
                    "first_signed_cr",
                    models.BooleanField(
                        default=False,
                        verbose_name="Signed FIRST Consent & Release (C&R)",
                    ),
                ),
                (
                    "first_registered_teams",
                    models.CharField(
                        blank=True,
                        help_text="Team numbers or names, comma-separated",
                        max_length=200,
                        null=True,
                        verbose_name="Registered team(s)",
                    ),
                ),
                (
                    "interest_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why are you interested in participating in this Girls of Steel program this season?",
                        null=True,
                        verbose_name="Interest reason",
                    ),
                ),
                (
                    "hoped_gains",
                    models.TextField(
                        blank=True,
                        help_text="What do you hope to gain from the experience?",
                        null=True,
                        verbose_name="Hoped gains",
                    ),
                ),
                (
                    "prior_robotics_experience",
                    models.TextField(
                        blank=True,
                        help_text="What prior robotics experience do you have? (No experience is necessary to be a part of the program.)",
                        null=True,
                        verbose_name="Prior robotics experience",
                    ),
                ),
                (
                    "referral_source",
                    models.TextField(
                        blank=True,
                        help_text="How did you hear about Girls of Steel Robotics?",
                        null=True,
                        verbose_name="Referral source",
                    ),
                ),
                (
                    "graduated",
                    models.BooleanField(
                        default=False, help_text="Check if this student has graduated."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "cell_phone", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_fbi_clearance", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_paca_clearance", "has_patch_clearance", "has_zoom_account", "home_phone", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "pa_clearances_expiration_date", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."cell_phone", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_fbi_clearance", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_paca_clearance", NEW."has_patch_clearance", NEW."has_zoom_account", NEW."home_phone", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."pa_clearances_expiration_date", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="4802ac733434fa05b2c870834e53d320d985e936",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4734c",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "cell_phone", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_fbi_clearance", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_paca_clearance", "has_patch_clearance", "has_zoom_account", "home_phone", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "pa_clearances_expiration_date", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."cell_phone", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_fbi_clearance", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_paca_clearance", NEW."has_patch_clearance", NEW."has_zoom_account", NEW."home_phone", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."pa_clearances_expiration_date", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="ba200bd9ee73e53ab08d568a91728f5f15918e61",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_19786",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adultstudentrelationship",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_adultstudentrelationshipevent" ("adult_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_to_student", "specific_relationship", "student_id") VALUES (NEW."adult_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."relationship_to_student", NEW."specific_relationship", NEW."student_id"); RETURN NULL;',
                    hash="c350b99f4a585be0266debf9cc99c70a3347f9cd",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_5b888",
                    table="programs_adultstudentrelationship",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adultstudentrelationship",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_adultstudentrelationshipevent" ("adult_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_to_student", "specific_relationship", "student_id") VALUES (NEW."adult_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."relationship_to_student", NEW."specific_relationship", NEW."student_id"); RETURN NULL;',
                    hash="f9f8a9d82d3f64d57fc2e3b289ea7683d8328c1b",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_a63ea",
                    table="programs_adultstudentrelationship",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="enrollment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_enrollmentevent" ("active", "created_at", "crew_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "student_id", "subteam_id", "team_id") VALUES (NEW."active", NEW."created_at", NEW."crew_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."program_id", NEW."student_id", NEW."subteam_id", NEW."team_id"); RETURN NULL;',
                    hash="4a2e915a9f3ac14276545df263555b219fb140b6",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_75e5e",
                    table="programs_enrollment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="enrollment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_enrollmentevent" ("active", "created_at", "crew_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "student_id", "subteam_id", "team_id") VALUES (NEW."active", NEW."created_at", NEW."crew_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."program_id", NEW."student_id", NEW."subteam_id", NEW."team_id"); RETURN NULL;',
                    hash="e2c92f95fc5d17fd12fa4605dd577ebab0d144b3",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_96a50",
                    table="programs_enrollment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "cell_phone_number", "city", "clearances_expiration_date", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "has_passed_clearances", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "photo", "primary_contact_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."cell_phone_number", NEW."city", NEW."clearances_expiration_date", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."has_passed_clearances", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."photo", NEW."primary_contact_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="b2b269d2e08f4cdc52b2800b22dea6a0f6f872ef",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_93b62",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "cell_phone_number", "city", "clearances_expiration_date", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "has_passed_clearances", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "photo", "primary_contact_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."cell_phone_number", NEW."city", NEW."clearances_expiration_date", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."has_passed_clearances", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."photo", NEW."primary_contact_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="b2b80a799a69a54a6eb9dc9d6034b5954cbdb8ac",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1b783",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="adultevent",
            name="andrew_id_sponsor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The Adult (mentor) who sponsored this Andrew ID.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="adultevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="adultevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="adultevent",
            name="student_record",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The student record this alumni profile originated from.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.student",
            ),
        ),
        migrations.AddField(
            model_name="adultevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adultstudentrelationshipevent",
            name="adult",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="adultstudentrelationshipevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="adultstudentrelationshipevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="programs.adultstudentrelationship",
            ),
        ),
        migrations.AddField(
            model_name="adultstudentrelationshipevent",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.student",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="crew",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.crew",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="programs.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="program",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.student",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="subteam",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.subteam",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.team",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="programs.student",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="school",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.school",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="secondary_contact",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
