# Generated by Django 5.2.15 on 2026-07-02 17:30

from django.db import migrations, models


def populate_app_dates(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    for p in Program.objects.all():
        changed = False
        if not p.applications_open and p.start_date:
            p.applications_open = p.start_date
            changed = True
        if not p.applications_close and p.end_date:
            p.applications_close = p.end_date
            changed = True
        if changed:
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0079_adultevent_adultstudentrelationshipevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="applications_close",
            field=models.DateField(
                blank=True,
                help_text="Date when applications close for this program. Defaults to program end date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="applications_open",
            field=models.DateField(
                blank=True,
                help_text="Date when applications open for this program. Defaults to program start date.",
                null=True,
            ),
        ),
        migrations.RunPython(populate_app_dates, migrations.RunPython.noop),
    ]
