# Generated by Django 5.2.15 on 2026-07-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0080_program_applications_close_program_applications_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Optional due date for the fee.", null=True
            ),
        ),
    ]
