# Generated by Django 5.2.15 on 2026-07-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0081_fee_due_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fee",
            old_name="date",
            new_name="effective_date",
        ),
        migrations.AlterField(
            model_name="fee",
            name="effective_date",
            field=models.DateField(
                blank=True,
                help_text="Effective date the fee was posted/received (used for balance sheet sorting).",
                null=True,
            ),
        ),
    ]
