# Generated by Django 5.2.15 on 2026-07-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0082_remove_fee_date_fee_effective_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adult",
            name="personal_email",
            field=models.EmailField(
                blank=True,
                help_text="Primary contact email (e.g. Gmail). Used for login and notifications.",
                max_length=254,
                null=True,
            ),
        ),
    ]
