# Generated by Django 5.2.15 on 2026-07-29 00:06

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0083_remove_adult_personal_email_unique"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="update_update",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="adultevent",
            name="phone_number",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "cell_phone", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_fbi_clearance", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_paca_clearance", "has_patch_clearance", "has_zoom_account", "home_phone", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "pa_clearances_expiration_date", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."cell_phone", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_fbi_clearance", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_paca_clearance", NEW."has_patch_clearance", NEW."has_zoom_account", NEW."home_phone", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."pa_clearances_expiration_date", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="6cda889b3be114a027d6d222cd77590cbc6a2818",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4734c",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "cell_phone", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_fbi_clearance", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_paca_clearance", "has_patch_clearance", "has_zoom_account", "home_phone", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "pa_clearances_expiration_date", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."cell_phone", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_fbi_clearance", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_paca_clearance", NEW."has_patch_clearance", NEW."has_zoom_account", NEW."home_phone", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."pa_clearances_expiration_date", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="6f6427dbe8252c069793e1a563c8f11fc98a5536",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_19786",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
    ]
