# Generated by Django 5.2.15 on 2026-07-29 01:03

import pgtrigger.compiler
import pgtrigger.migrations
import programs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0084_remove_adult_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='adult',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='adult',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='update_update',
        ),
        migrations.AddField(
            model_name='adult',
            name='can_receive_texts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adult',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[programs.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='adult',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('cell', 'Cell'), ('work', 'Work'), ('other', 'Other')], default='cell', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adultevent',
            name='can_receive_texts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adultevent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[programs.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='adultevent',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('cell', 'Cell'), ('work', 'Work'), ('other', 'Other')], default='cell', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='can_receive_texts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[programs.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('cell', 'Cell'), ('work', 'Work'), ('other', 'Other')], default='cell', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='can_receive_texts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[programs.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('cell', 'Cell'), ('work', 'Work'), ('other', 'Other')], default='cell', max_length=20, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='adult',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "cell_phone", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_fbi_clearance", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_paca_clearance", "has_patch_clearance", "has_zoom_account", "home_phone", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "pa_clearances_expiration_date", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."cell_phone", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_fbi_clearance", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_paca_clearance", NEW."has_patch_clearance", NEW."has_zoom_account", NEW."home_phone", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."pa_clearances_expiration_date", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;', hash='298fa785ce35b7a8b1bb81071a850227a7695572', operation='INSERT', pgid='pgtrigger_insert_insert_4734c', table='programs_adult', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='adult',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "cell_phone", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_fbi_clearance", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_paca_clearance", "has_patch_clearance", "has_zoom_account", "home_phone", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "pa_clearances_expiration_date", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."cell_phone", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_fbi_clearance", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_paca_clearance", NEW."has_patch_clearance", NEW."has_zoom_account", NEW."home_phone", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."pa_clearances_expiration_date", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;', hash='023ca28f3d67e1c2ec5a680803a11c286e8ebf1e', operation='UPDATE', pgid='pgtrigger_update_update_19786', table='programs_adult', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "can_receive_texts", "cell_phone_number", "city", "clearances_expiration_date", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "has_passed_clearances", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."can_receive_texts", NEW."cell_phone_number", NEW."city", NEW."clearances_expiration_date", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."has_passed_clearances", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;', hash='3922fbd2fe8cdb4b2b26d6f80e9121eb10f13e96', operation='INSERT', pgid='pgtrigger_insert_insert_93b62', table='programs_student', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "can_receive_texts", "cell_phone_number", "city", "clearances_expiration_date", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "has_passed_clearances", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."can_receive_texts", NEW."cell_phone_number", NEW."city", NEW."clearances_expiration_date", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."has_passed_clearances", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;', hash='1d739e173f023bbdf95c572aa8b6fc613e7a16ad', operation='UPDATE', pgid='pgtrigger_update_update_1b783', table='programs_student', when='AFTER')),
        ),
    ]
