# Generated by Django 5.2.15 on 2026-07-29 01:04

from django.db import migrations


def migrate_phones(apps, schema_editor):
    Adult = apps.get_model("programs", "Adult")
    for adult in Adult.objects.all():
        if getattr(adult, "cell_phone", None):
            adult.phone_number = adult.cell_phone
            adult.phone_type = "cell"
            adult.can_receive_texts = True
            adult.save()
        elif getattr(adult, "home_phone", None):
            adult.phone_number = adult.home_phone
            adult.phone_type = "home"
            adult.can_receive_texts = False
            adult.save()

    Student = apps.get_model("programs", "Student")
    for student in Student.objects.all():
        if getattr(student, "cell_phone_number", None):
            student.phone_number = student.cell_phone_number
            student.phone_type = "cell"
            student.can_receive_texts = True
            student.save()


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0085_remove_adult_insert_insert_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_phones),
    ]
