# Generated by Django 5.2.15 on 2026-07-29 01:27

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0086_migrate_phone_data"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="update_update",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="cell_phone",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="home_phone",
        ),
        migrations.RemoveField(
            model_name="adultevent",
            name="cell_phone",
        ),
        migrations.RemoveField(
            model_name="adultevent",
            name="home_phone",
        ),
        migrations.RemoveField(
            model_name="student",
            name="cell_phone_number",
        ),
        migrations.RemoveField(
            model_name="studentevent",
            name="cell_phone_number",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_fbi_clearance", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_paca_clearance", "has_patch_clearance", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "pa_clearances_expiration_date", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_fbi_clearance", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_paca_clearance", NEW."has_patch_clearance", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."pa_clearances_expiration_date", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="603672b405feaff64fb74a19d2fd6f9210cd8536",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4734c",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_fbi_clearance", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_paca_clearance", "has_patch_clearance", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "pa_clearances_expiration_date", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_fbi_clearance", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_paca_clearance", NEW."has_patch_clearance", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."pa_clearances_expiration_date", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="ca2acb9e89f74ed80876fecd9bc062905e718a88",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_19786",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "can_receive_texts", "city", "clearances_expiration_date", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "has_passed_clearances", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."can_receive_texts", NEW."city", NEW."clearances_expiration_date", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."has_passed_clearances", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="602bdc20b8c538e468db2807ef08a2c2a46c86ff",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_93b62",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "can_receive_texts", "city", "clearances_expiration_date", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "has_passed_clearances", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."can_receive_texts", NEW."city", NEW."clearances_expiration_date", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."has_passed_clearances", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="9998b0ca15e8cb6eeb5fb81b6da2bf276502b027",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1b783",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
    ]
