# Generated by Django 5.2.15 on 2026-07-31 05:00

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_is_pending_to_status(apps, schema_editor):
    """Carry forward the old is_pending flag onto the new status field before
    is_pending is removed (True -> pending; False -> approved, matching the
    field's new default)."""
    SlidingScale = apps.get_model("programs", "SlidingScale")
    SlidingScale.objects.filter(is_pending=True).update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0087_remove_adult_insert_insert_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlidingScaleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10150.00"),
                        help_text="Federal poverty guideline base amount (for household size).",
                        max_digits=10,
                    ),
                ),
                (
                    "additional_member_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5500.00"),
                        help_text="Amount added per household member when computing the poverty guideline base.",
                        max_digits=10,
                    ),
                ),
                (
                    "low_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.50"),
                        help_text="Multiplier applied to the poverty guideline base to compute the lower income boundary.",
                        max_digits=5,
                    ),
                ),
                (
                    "high_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("4.00"),
                        help_text="Multiplier applied to the poverty guideline base to compute the upper income boundary.",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sliding Scale Settings",
                "verbose_name_plural": "Sliding Scale Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="slidingscale",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="slidingscale",
            name="slidingscale_stu_prog_idx",
        ),
        migrations.AlterUniqueTogether(
            name="slidingscale",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="slidingscale",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent who submitted this application, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sliding_scale_applications",
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="slidingscale",
            name="decline_reason",
            field=models.TextField(
                blank=True,
                help_text="Shown to the parent when the application is declined.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="slidingscale",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Date the discount stops applying. Leave blank for no expiration.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="slidingscale",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slidingscale",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="slidingscale",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
        migrations.RunPython(migrate_is_pending_to_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="slidingscale",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Effective start date. Only fees on or after this date (and before the expiration date, if any) will be discounted.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="slidingscale",
            name="family_size",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Household size"
            ),
        ),
        migrations.AlterField(
            model_name="slidingscale",
            name="percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percent discount applied to total fees (0–100), across all of the student's programs.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="slidingscale",
            index=models.Index(fields=["student"], name="slidingscale_student_idx"),
        ),
        migrations.AddIndex(
            model_name="slidingscale",
            index=models.Index(fields=["status"], name="slidingscale_status_idx"),
        ),
        migrations.RemoveField(
            model_name="slidingscale",
            name="is_pending",
        ),
        migrations.RemoveField(
            model_name="slidingscale",
            name="program",
        ),
    ]
