# Generated by Django 5.2.15 on 2026-08-06 21:24

from django.db import migrations


def grant_mentor_attendance_write(apps, schema_editor):
    """Mentors need write access to attendance so they can close stale sessions
    and manage RFID cards. Deletion stays blocked via can_user_delete()."""
    RolePermission = apps.get_model("programs", "RolePermission")
    RolePermission.objects.update_or_create(
        role="Mentor",
        section="attendance",
        defaults={"can_read": True, "can_write": True},
    )


def revoke_mentor_attendance_write(apps, schema_editor):
    RolePermission = apps.get_model("programs", "RolePermission")
    RolePermission.objects.filter(role="Mentor", section="attendance").update(
        can_write=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0088_sliding_scale_refactor"),
    ]

    operations = [
        migrations.RunPython(
            grant_mentor_attendance_write, revoke_mentor_attendance_write
        ),
    ]
