# Generated by Django 5.2.15 on 2026-08-09 22:09

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


def flush_deferred_fk_checks(apps, schema_editor):
    """Flush deferred FK checks so the legacy columns can be dropped.

    The backfill above updates the newly-added relationship FK columns, which
    Django created DEFERRABLE INITIALLY DEFERRED. On PostgreSQL those updates
    queue deferred checks as pending trigger events, so the RemoveField /
    DROP CONSTRAINT operations below fail with "cannot ALTER TABLE ... because
    it has pending trigger events". Forcing all constraints immediate here
    (PostgreSQL only) consumes those events before the ALTERs run.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def link_relationships_from_old_contacts(apps, schema_editor):
    """Point Student.primary/secondary_contact_relationship at the ASR rows.

    Migration 0090 backfilled AdultStudentRelationship rows from the legacy
    Student.primary_contact / secondary_contact FKs. This migration swaps the
    Student-side pointers to reference those ASR rows directly, creating the
    row on the fly if anything slipped through, and marks the linked Adults as
    parents.

    Access is done via getattr() so the same function can be exercised in
    tests against the live (post-refactor) model, where the legacy FK columns
    only exist as properties.
    """
    Student = apps.get_model("programs", "Student")
    AdultStudentRelationship = apps.get_model("programs", "AdultStudentRelationship")
    Adult = apps.get_model("programs", "Adult")

    adult_ids = set()
    for student in Student.objects.all().iterator():
        for slot in ("primary", "secondary"):
            adult_pk = getattr(student, f"{slot}_contact_id", None)
            if not adult_pk:
                continue
            rel, _ = AdultStudentRelationship.objects.get_or_create(
                adult_id=adult_pk,
                student_id=student.pk,
                defaults={"relationship_to_student": "parent"},
            )
            if getattr(student, f"{slot}_contact_relationship_id") != rel.pk:
                setattr(student, f"{slot}_contact_relationship_id", rel.pk)
                student.save(update_fields=[f"{slot}_contact_relationship_id"])
            adult_ids.add(adult_pk)

    if adult_ids:
        Adult.objects.filter(pk__in=adult_ids).update(is_parent=True)


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0090_backfill_student_parent_links"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="update_update",
        ),
        migrations.AddField(
            model_name="student",
            name="primary_contact_relationship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_with_primary",
                to="programs.adultstudentrelationship",
                verbose_name="Primary contact relationship",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="secondary_contact_relationship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_with_secondary",
                to="programs.adultstudentrelationship",
                verbose_name="Secondary contact relationship",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="primary_contact_relationship",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.adultstudentrelationship",
                verbose_name="Primary contact relationship",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="secondary_contact_relationship",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.adultstudentrelationship",
                verbose_name="Secondary contact relationship",
            ),
        ),
        migrations.RunPython(
            link_relationships_from_old_contacts, migrations.RunPython.noop
        ),
        migrations.RunPython(flush_deferred_fk_checks, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="student",
            name="primary_contact",
        ),
        migrations.RemoveField(
            model_name="student",
            name="secondary_contact",
        ),
        migrations.RemoveField(
            model_name="studentevent",
            name="primary_contact",
        ),
        migrations.RemoveField(
            model_name="studentevent",
            name="secondary_contact",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "can_receive_texts", "city", "clearances_expiration_date", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "has_passed_clearances", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."can_receive_texts", NEW."city", NEW."clearances_expiration_date", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."has_passed_clearances", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="009ce798b06e28945e9cb0e30581ec2ded567e59",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_93b62",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "can_receive_texts", "city", "clearances_expiration_date", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "has_passed_clearances", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."can_receive_texts", NEW."city", NEW."clearances_expiration_date", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."has_passed_clearances", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="c96f37dce4a5937d3f7ff7e305641f20c1c8cc75",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1b783",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
    ]
