# Generated by Django 5.2.15 on 2026-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0091_refactor_student_parent_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressGeocode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized address string used as the cache key.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        help_text="Latitude of the address, or null if it could not be geocoded.",
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        help_text="Longitude of the address, or null if it could not be geocoded.",
                        null=True,
                    ),
                ),
                (
                    "found",
                    models.BooleanField(
                        default=False,
                        help_text="True if the geocoder returned a result for this address.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
