# Generated by Django 5.2.16 on 2026-08-09 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0091_refactor_student_parent_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='slidingscale',
            index=models.Index(fields=['student', 'status', 'date', 'expiration_date'], name='slidingscale_active_lookup_idx'),
        ),
    ]
