# Generated by Django 5.2.16 on 2026-08-10 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0092_slidingscale_slidingscale_active_lookup_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            (
                                "state_police",
                                "PA State Police Criminal History (PATCH)",
                            ),
                            ("child_abuse", "PA Child Abuse History (Act 151)"),
                            ("fbi", "FBI Fingerprint (Act 114)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cleared",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this clearance has been obtained and passed.",
                    ),
                ),
                (
                    "obtained_date",
                    models.DateField(
                        blank=True,
                        help_text="When this clearance was obtained (becomes active). Expiration is calculated automatically.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["check_type"],
            },
        ),
        migrations.AddField(
            model_name="backgroundcheck",
            name="adult",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="background_checks",
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="backgroundcheck",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="background_checks",
                to="programs.student",
            ),
        ),
    ]
