# Generated by Django 5.2.16 on 2026-08-10 00:09

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0094_migrate_adult_clearances"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="enrollment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="enrollment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="update_update",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="has_fbi_clearance",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="has_paca_clearance",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="has_patch_clearance",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="pa_clearances_expiration_date",
        ),
        migrations.RemoveField(
            model_name="adultevent",
            name="has_fbi_clearance",
        ),
        migrations.RemoveField(
            model_name="adultevent",
            name="has_paca_clearance",
        ),
        migrations.RemoveField(
            model_name="adultevent",
            name="has_patch_clearance",
        ),
        migrations.RemoveField(
            model_name="adultevent",
            name="pa_clearances_expiration_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="clearances_expiration_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="has_passed_clearances",
        ),
        migrations.RemoveField(
            model_name="studentevent",
            name="clearances_expiration_date",
        ),
        migrations.RemoveField(
            model_name="studentevent",
            name="has_passed_clearances",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="clearance_due",
            field=models.BooleanField(
                default=False,
                help_text="Set when the enrolled student requires PA background clearances and is missing at least one valid clearance.",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="clearance_due",
            field=models.BooleanField(
                default=False,
                help_text="Set when the enrolled student requires PA background clearances and is missing at least one valid clearance.",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="470df7f817d956a4a6b676c7246a9a81aea749c7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4734c",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_adultevent" ("active", "address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."active", NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="46d5eea28ed1a4666b7cf2c6c93582ed38085024",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_19786",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="enrollment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_enrollmentevent" ("active", "clearance_due", "created_at", "crew_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "student_id", "subteam_id", "team_id") VALUES (NEW."active", NEW."clearance_due", NEW."created_at", NEW."crew_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."program_id", NEW."student_id", NEW."subteam_id", NEW."team_id"); RETURN NULL;',
                    hash="87ac8f6f84a84568b5de915d38a9e97e1cece984",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_75e5e",
                    table="programs_enrollment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="enrollment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_enrollmentevent" ("active", "clearance_due", "created_at", "crew_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "student_id", "subteam_id", "team_id") VALUES (NEW."active", NEW."clearance_due", NEW."created_at", NEW."crew_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."program_id", NEW."student_id", NEW."subteam_id", NEW."team_id"); RETURN NULL;',
                    hash="ffff865612b4949a0cfb1a12e4f5900fb4315057",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_96a50",
                    table="programs_enrollment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "can_receive_texts", "city", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."can_receive_texts", NEW."city", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="a1bdf2a8224626e1d1c07a3e25cc06de283f8e2b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_93b62",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "can_receive_texts", "city", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."can_receive_texts", NEW."city", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="fb65aa8267d13ef0c08a77a0e4ab5767d5d00aa5",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1b783",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
    ]
