# Generated by Django 5.2.15 on 2026-08-13 17:52

from django.db import migrations, models

import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0096_addressgeocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adult",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=programs.models._adult_photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="adultevent",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=programs.models._adult_photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="programdocument",
            name="file",
            field=models.FileField(
                help_text="The blank PDF (or other file) for the applicant to download and fill out.",
                max_length=255,
                upload_to=programs.models._program_document_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=programs.models._student_photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="studentevent",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=programs.models._student_photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="taxform",
            name="file",
            field=programs.models.EncryptedFileField(
                help_text="Uploaded tax form for sliding scale verification. Will be deleted after review.",
                max_length=255,
                upload_to=programs.models._tax_form_upload_to,
            ),
        ),
    ]
