# Generated by Django 5.2.15 on 2026-08-13 21:39

import django.db.models.deletion
import programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0097_alter_adult_photo_alter_adultevent_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=programs.models._student_document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='programs.programdocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_documents', to='programs.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('student', 'program_document')},
            },
        ),
    ]
