# Generated by Django 5.2.15 on 2026-08-17 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0099_alter_rolepermission_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    models.TextField(help_text="Markdown content of the agreement."),
                ),
                ("effective_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mentor Agreement",
                "verbose_name_plural": "Mentor Agreements",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="MentorAgreementAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the acceptor (for audit trail).",
                        null=True,
                    ),
                ),
                (
                    "adult",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_acceptances",
                        to="programs.adult",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptances",
                        to="programs.mentoragreement",
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
                "unique_together": {("adult", "agreement")},
            },
        ),
    ]
