# Generated by Django 5.2.15 on 2026-08-17 20:03

import django.db.models.deletion
import programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0101_expand_mentor_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoragreement',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown content of the agreement. Leave blank for document-only agreements.'),
        ),
        migrations.AlterField(
            model_name='mentoragreement',
            name='document',
            field=models.FileField(blank=True, help_text='Uploaded document (PDF, etc.) for the agreement. Leave blank for markdown-only agreements.', max_length=255, upload_to=programs.models._mentor_agreement_upload_to),
        ),
        migrations.CreateModel(
            name='MentorAgreementSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=programs.models._agreement_submission_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_submissions', to='programs.adult')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='programs.mentoragreement')),
            ],
            options={
                'verbose_name': 'Mentor Agreement Submission',
                'verbose_name_plural': 'Mentor Agreement Submissions',
                'ordering': ['-uploaded_at'],
                'unique_together': {('adult', 'agreement')},
            },
        ),
    ]
