# Generated by Django 5.2.15 on 2026-08-18 04:13

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0102_expand_mentor_agreement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="update_update",
        ),
        migrations.RemoveIndex(
            model_name="adult",
            name="adult_parent_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="adult",
            name="adult_mentor_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="adult",
            name="adult_alumni_active_idx",
        ),
        migrations.RemoveField(
            model_name="adult",
            name="active",
        ),
        migrations.RemoveField(
            model_name="adultevent",
            name="active",
        ),
        migrations.AddField(
            model_name="adult",
            name="login_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Uncheck to disable this person's portal login.",
            ),
        ),
        migrations.AddField(
            model_name="adult",
            name="mentor_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Uncheck to mark this person as an inactive mentor.",
            ),
        ),
        migrations.AddField(
            model_name="adultevent",
            name="login_enabled",
            field=models.BooleanField(
                default=True, help_text="Uncheck to disable this person's portal login."
            ),
        ),
        migrations.AddField(
            model_name="adultevent",
            name="mentor_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to mark this person as an inactive mentor.",
            ),
        ),
        migrations.AddIndex(
            model_name="adult",
            index=models.Index(
                fields=["is_parent", "login_enabled"], name="adult_parent_login_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adult",
            index=models.Index(
                fields=["is_mentor", "mentor_active"], name="adult_mentor_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adult",
            index=models.Index(
                fields=["is_alumni", "login_enabled"], name="adult_alumni_login_idx"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_adultevent" ("address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "login_enabled", "mentor_active", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."login_enabled", NEW."mentor_active", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="0c5b1a63197bb9900d55009e9f392ef52e94c3e1",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4734c",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_adultevent" ("address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "first_name", "has_cmu_building_access", "has_cmu_id_card", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "login_enabled", "mentor_active", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."first_name", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."login_enabled", NEW."mentor_active", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="0839c3970e8b847f78878cdd39839c793499d880",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_19786",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
    ]
