# Generated by Django 5.2.16 on 2026-08-19 16:15

import django.db.models.deletion
from django.db import migrations, models


def backfill_districts(apps, schema_editor):
    School = apps.get_model("programs", "School")
    SchoolDistrict = apps.get_model("programs", "SchoolDistrict")
    for school in School.objects.all():
        raw = school.district_id
        if not raw:
            continue
        district, _ = SchoolDistrict.objects.get_or_create(name=str(raw))
        school.district = district
        school.save()


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0103_rename_active_to_login_enabled_add_mentor_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='programs.schooldistrict', verbose_name='School district'),
        ),
        migrations.RunPython(backfill_districts, migrations.RunPython.noop),
    ]
