# Generated by Django 5.2.16 on 2026-08-22 00:57

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0105_add_outreach_feature"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="update_update",
        ),
        migrations.AddField(
            model_name="student",
            name="andrew_id_expiration",
            field=models.DateField(
                blank=True, help_text="Expiration date of this Andrew ID.", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="andrew_id_sponsor",
            field=models.ForeignKey(
                blank=True,
                help_text="The Adult (mentor) who sponsored this Andrew ID.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sponsored_student_andrew_ids",
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="andrew_id_expiration",
            field=models.DateField(
                blank=True, help_text="Expiration date of this Andrew ID.", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="andrew_id_sponsor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The Adult (mentor) who sponsored this Andrew ID.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="programs.adult",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="c434a561636edbaaf79d8be7606fe705c89e89f1",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_93b62",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_name", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_name", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="f90db4d6211dbc432fb33a21389cf947783e10d5",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1b783",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
    ]
