# Generated by Django 5.2.17 on 2026-08-27 05:10

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0109_normalize_name_fields_add_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adult",
            options={"ordering": ["last_name", "legal_first_name"]},
        ),
        migrations.AlterModelOptions(
            name="feeassignment",
            options={
                "ordering": [
                    "fee__program__name",
                    "fee__name",
                    "student__last_name",
                    "student__preferred_first_name",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["preferred_first_name", "last_name"]},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="update_update",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="adult",
                    name="adult_name_idx",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS adult_name_idx",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="student",
                    name="student_name_idx",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS student_name_idx",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.RenameField(
            model_name="adultevent",
            old_name="first_name",
            new_name="legal_first_name",
        ),
        migrations.RenameField(
            model_name="studentevent",
            old_name="first_name",
            new_name="preferred_first_name",
        ),
        migrations.AlterField(
            model_name="studentevent",
            name="preferred_first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Preferred first name",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="preferred_first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Preferred first name",
            ),
        ),
        migrations.AlterField(
            model_name="adultevent",
            name="preferred_first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Preferred first name",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="section",
            field=models.CharField(
                choices=[
                    ("student_info", "Student - Info (General)"),
                    ("identity", "Student - Identity"),
                    ("contact_address", "Student - Contact & Address"),
                    ("health_medical", "Student - Health & Medical"),
                    ("school", "Student - School"),
                    ("cmu_andrew", "Student - CMU Andrew ID"),
                    ("background_checks", "Student - Background Checks"),
                    ("student_documents", "Student - Signed Documents"),
                    ("discord", "Student - Discord"),
                    ("first_website", "Student - FIRST Website"),
                    ("parents_emergency", "Student - Parents/Emergency Contacts"),
                    ("other_details", "Student - Other Details"),
                    ("attendance", "Student - Attendance"),
                    ("adult_info", "Adult - Info"),
                    ("payments", "Payments - General"),
                    ("sliding_scale", "Payments - Sliding Scale"),
                    ("fees", "Programs - Fees"),
                    ("programs", "Programs - General"),
                    ("team_assignments", "Programs - Team Assignments"),
                    ("badge_award", "Badges - Award"),
                    ("badge_manage", "Badges - Create / Manage"),
                ],
                max_length=50,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="adult",
                    index=models.Index(
                        fields=["last_name", "legal_first_name"],
                        name="adult_name_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX adult_name_idx ON programs_adult (last_name, legal_first_name)",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="student",
                    index=models.Index(
                        fields=["last_name", "preferred_first_name"],
                        name="student_name_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX student_name_idx ON programs_student (last_name, preferred_first_name)",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_adultevent" ("address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "has_cmu_building_access", "has_cmu_id_card", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "legal_first_name", "login_enabled", "mentor_active", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."legal_first_name", NEW."login_enabled", NEW."mentor_active", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="8eb042279bbef97ba53b313e76fa4957a90b5c2e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4734c",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_adultevent" ("address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "has_cmu_building_access", "has_cmu_id_card", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "legal_first_name", "login_enabled", "mentor_active", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."legal_first_name", NEW."login_enabled", NEW."mentor_active", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="b97a540bf0dfdca3c701d42e18e8f59ea34456ad",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_19786",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="51ab63d79e77ac9e590a3a79434fbf024ed9224c",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_93b62",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="c401cf257091b5f3121d5323a2c9c125bf94f4d7",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1b783",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
    ]
