# Generated by Django 5.2.17 on 2026-08-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0110_alter_adult_options_alter_feeassignment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adultevent",
            name="legal_first_name",
            field=models.CharField(max_length=150, verbose_name="Legal first name"),
        ),
    ]
