# Generated by Django 6.1 on 2026-08-29 17:44

from django.db import migrations

# The single "Parent sign-outs" feature now gates BOTH the printable sign-out
# sheet and the digital sign-out station. Existing DBs still have the old
# "Printable Sign-out Sheet" name (created in 0041); rename it in place.
NAME = "Parent sign-outs"
DESCRIPTION = (
    "Enable parent sign-outs: the printable sign-out sheet on the Program "
    "page and the digital sign-out station on the tablet."
)


def rename_signout_feature(apps, schema_editor):
    ProgramFeature = apps.get_model("programs", "ProgramFeature")
    ProgramFeature.objects.filter(key="signout-sheet").update(
        name=NAME, description=DESCRIPTION
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0111_alter_adultevent_legal_first_name"),
    ]

    operations = [
        migrations.RunPython(rename_signout_feature, noop_reverse),
    ]
