# Generated by Django 6.1 on 2026-09-15 19:34

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("programs", "0117_alter_rolepermission_section"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="adult",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="enrollment",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="enrollment",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="student",
            name="update_update",
        ),
        migrations.AddField(
            model_name="adult",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this adult (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adults",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="adultevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organization that owns this adult (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="backgroundcheck",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this background check (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background_checks",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this enrollment (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organization that owns this enrollment (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="fee",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this fee (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fees",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="feeassignment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this fee assignment (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_assignments",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this payment (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this program (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programs",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="slidingscale",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this sliding-scale application (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sliding_scales",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this student (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="studentevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organization that owns this student (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="organizations.organization",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_adultevent" ("address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "has_cmu_building_access", "has_cmu_id_card", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "legal_first_name", "login_enabled", "mentor_active", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "organization_id", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."legal_first_name", NEW."login_enabled", NEW."mentor_active", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."organization_id", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="98cbefc49b4f3804fd30a2719ff16ce824324da3",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_4734c",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="adult",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_adultevent" ("address", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "college", "created_at", "discord_username", "email_updates", "emergency_contact_name", "emergency_contact_phone", "employer", "field_of_study", "has_cmu_building_access", "has_cmu_id_card", "has_google_admin_drive_access", "has_google_mentor_drive_access", "has_google_team_drive_access", "has_zoom_account", "id", "in_onshape_classroom", "is_alumni", "is_mentor", "is_parent", "job_title", "last_name", "legal_first_name", "login_enabled", "mentor_active", "notes", "ok_to_contact", "on_canva", "on_canvas", "on_discord", "on_first_website", "on_google_field_crew_group", "on_google_mentor_group", "organization_id", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "pronouns", "role", "signed_first_consent_form", "start_year", "state", "student_record_id", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."college", NEW."created_at", NEW."discord_username", NEW."email_updates", NEW."emergency_contact_name", NEW."emergency_contact_phone", NEW."employer", NEW."field_of_study", NEW."has_cmu_building_access", NEW."has_cmu_id_card", NEW."has_google_admin_drive_access", NEW."has_google_mentor_drive_access", NEW."has_google_team_drive_access", NEW."has_zoom_account", NEW."id", NEW."in_onshape_classroom", NEW."is_alumni", NEW."is_mentor", NEW."is_parent", NEW."job_title", NEW."last_name", NEW."legal_first_name", NEW."login_enabled", NEW."mentor_active", NEW."notes", NEW."ok_to_contact", NEW."on_canva", NEW."on_canvas", NEW."on_discord", NEW."on_first_website", NEW."on_google_field_crew_group", NEW."on_google_mentor_group", NEW."organization_id", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."pronouns", NEW."role", NEW."signed_first_consent_form", NEW."start_year", NEW."state", NEW."student_record_id", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="94999e2a2af6dd26c36cc24f55c59a57f27bf08e",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_19786",
                    table="programs_adult",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="enrollment",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_enrollmentevent" ("active", "clearance_due", "created_at", "crew_id", "id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "student_id", "subteam_id", "team_id") VALUES (NEW."active", NEW."clearance_due", NEW."created_at", NEW."crew_id", NEW."id", NEW."organization_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."program_id", NEW."student_id", NEW."subteam_id", NEW."team_id"); RETURN NULL;',
                    hash="f33ba55cfc8c78a8ac3d901b3d0d2283867457ec",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_75e5e",
                    table="programs_enrollment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="enrollment",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_enrollmentevent" ("active", "clearance_due", "created_at", "crew_id", "id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "program_id", "student_id", "subteam_id", "team_id") VALUES (NEW."active", NEW."clearance_due", NEW."created_at", NEW."crew_id", NEW."id", NEW."organization_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."program_id", NEW."student_id", NEW."subteam_id", NEW."team_id"); RETURN NULL;',
                    hash="1d020276f9c0f6a828293840f2d8107794076561",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_96a50",
                    table="programs_enrollment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "organization_id", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."organization_id", NEW."personal_email", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="79f06fb5eac249a4d7ecf51be7bd6e78b318084f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_93b62",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="student",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "programs_studentevent" ("address", "allergies", "andrew_email", "andrew_id", "andrew_id_expiration", "andrew_id_sponsor_id", "can_receive_texts", "city", "created_at", "date_of_birth", "dietary_restrictions", "directory_consent", "discord_handle", "first_attached_to_parent_account", "first_has_account", "first_registered_teams", "first_signed_cr", "graduated", "graduation_year", "hoped_gains", "id", "interest_reason", "last_name", "legal_first_name", "medical_notes", "on_discord", "organization_id", "personal_email", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "phone_type", "photo", "preferred_first_name", "primary_contact_relationship_id", "prior_robotics_experience", "pronouns", "referral_source", "school_id", "secondary_contact_relationship_id", "seen_once", "state", "tshirt_size", "updated_at", "user_id", "zip_code") VALUES (NEW."address", NEW."allergies", NEW."andrew_email", NEW."andrew_id", NEW."andrew_id_expiration", NEW."andrew_id_sponsor_id", NEW."can_receive_texts", NEW."city", NEW."created_at", NEW."date_of_birth", NEW."dietary_restrictions", NEW."directory_consent", NEW."discord_handle", NEW."first_attached_to_parent_account", NEW."first_has_account", NEW."first_registered_teams", NEW."first_signed_cr", NEW."graduated", NEW."graduation_year", NEW."hoped_gains", NEW."id", NEW."interest_reason", NEW."last_name", NEW."legal_first_name", NEW."medical_notes", NEW."on_discord", NEW."organization_id", NEW."personal_email", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."phone_type", NEW."photo", NEW."preferred_first_name", NEW."primary_contact_relationship_id", NEW."prior_robotics_experience", NEW."pronouns", NEW."referral_source", NEW."school_id", NEW."secondary_contact_relationship_id", NEW."seen_once", NEW."state", NEW."tshirt_size", NEW."updated_at", NEW."user_id", NEW."zip_code"); RETURN NULL;',
                    hash="d755ad5605712d8714f484f27b81e84361319b59",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1b783",
                    table="programs_student",
                    when="AFTER",
                ),
            ),
        ),
    ]
