# Generated by Django 6.1 on 2026-09-07 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=500, verbose_name="Website"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Contact phone"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor_name",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of the vendor name (from the reference list, or the 'Not listed' name a student typed). Kept so order text survives a vendor being renamed or deleted.",
                max_length=255,
                verbose_name="Vendor name",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor_url",
            field=models.URLField(
                blank=True,
                help_text="Snapshot of the vendor website (reference list or custom).",
                max_length=500,
                verbose_name="Vendor website",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="The reference-list vendor for this order (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.vendor",
                verbose_name="Vendor",
            ),
        ),
    ]
