# Generated by Django 6.1 on 2026-09-07 04:17

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_vendor_purchaseorder_vendor_name_and_more"),
        ("programs", "0113_add_orders_feature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the vendor name (from the reference list, or the 'Not listed' name a mentor typed). Kept so order text survives a vendor being renamed or deleted.",
                        max_length=255,
                        verbose_name="Vendor name",
                    ),
                ),
                (
                    "vendor_url",
                    models.URLField(
                        blank=True,
                        help_text="Snapshot of the vendor website (reference list or custom).",
                        max_length=500,
                        verbose_name="Vendor website",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ordered", "Ordered")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ordered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ordered on"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_marked_ordered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Marked ordered by",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Program this order is being placed for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="programs.program",
                        verbose_name="Program",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The reference-list vendor this order is placed with (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.vendor",
                        verbose_name="Vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255, verbose_name="Item")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="How many you need. Decimal quantities (e.g. 2.5 ft of extrusion) are fine.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated price per item — helpful for budgeting. Leave blank if unknown.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Unit price",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="A URL to the part, tool, or product page.",
                        max_length=500,
                        verbose_name="Link to item",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Requested on"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="The order this item was grouped into. Items with no order are still awaiting grouping.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Program this item was requested from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="programs.program",
                        verbose_name="Program",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.DeleteModel(
            name="PurchaseOrder",
        ),
    ]
