# Generated by Django 6.1 on 2026-09-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_orderitem_delete_purchaseorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_estimate",
            field=models.DateField(
                blank=True,
                help_text="Expected delivery date from the carrier.",
                null=True,
                verbose_name="Estimated delivery",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_date",
            field=models.DateField(
                blank=True,
                help_text="Date the order left the vendor.",
                null=True,
                verbose_name="Shipped on",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.CharField(
                blank=True,
                help_text="Carrier used to ship this order (e.g. UPS, FedEx, USPS).",
                max_length=100,
                verbose_name="Shipping company",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Tracking number"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ready to place order"),
                    ("ordered", "Ordered"),
                    ("shipped", "Shipped"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
