# Generated by Django 6.1 on 2026-09-07 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_delivery_estimate_order_shipped_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="The reference-list vendor this item is requested from (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="orders.vendor",
                verbose_name="Vendor",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="vendor_name",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of the requested vendor's name (from the reference list, or the 'Not listed' name a requester typed). Kept so the request's text survives a vendor being renamed or deleted.",
                max_length=255,
                verbose_name="Vendor name",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="vendor_url",
            field=models.URLField(
                blank=True,
                help_text="Snapshot of the requested vendor's website (reference list or custom).",
                max_length=500,
                verbose_name="Vendor website",
            ),
        ),
    ]
