# Generated by Django 6.1 on 2026-09-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderitem_vendor_orderitem_vendor_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ready to place order"),
                    ("ordered", "Ordered"),
                    ("shipped", "Shipped"),
                    ("received", "Received"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
