# Generated by Django 6.1 on 2026-09-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_shippingcarrier_itemtag_tax"),
        ("programs", "0115_alter_rolepermission_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="tag",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="crew",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional crew/project this item is requested for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="programs.crew",
                verbose_name="Crew",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="subteam",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional subteam this item is requested for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="programs.subteam",
                verbose_name="Subteam",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional team this item is requested for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="programs.team",
                verbose_name="Team",
            ),
        ),
        migrations.DeleteModel(
            name="ItemTag",
        ),
    ]
