# Generated by Django 5.2.15 on 2026-07-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        (
            "attendance",
            "0002_rename_attendance_program_student_time_idx_attendance__program_686436_idx_and_more",
        ),
        ("programs", "0083_remove_adult_personal_email_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name for this kiosk (e.g. 'Build Space Entry').",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive kiosks return a 404 page."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        help_text="API key (write scope) used by this kiosk to record taps.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kiosk_configs",
                        to="api.apiclientkey",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Program that attendance will be recorded under.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kiosk_configs",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Configuration",
                "verbose_name_plural": "Kiosk Configurations",
                "ordering": ["label"],
            },
        ),
    ]
