# Generated by Django 5.2.15 on 2026-07-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_add_kiosk_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceevent",
            name="visitor_team_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="FRC/FTC/FLL team number for visiting teams.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="visitor_team_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="FRC/FTC/FLL team number for visiting teams.",
                null=True,
            ),
        ),
    ]
