# Generated by Django 5.2.15 on 2026-07-28 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_remove_kioskconfig_api_key"),
        ("programs", "0083_remove_adult_personal_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceevent",
            name="adult",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="adult",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="programs.adult",
            ),
        ),
        migrations.AddField(
            model_name="rfidcard",
            name="adult",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rfid_cards",
                to="programs.adult",
            ),
        ),
        migrations.AlterField(
            model_name="rfidcard",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rfid_cards",
                to="programs.student",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["program", "adult", "occurred_at"],
                name="attendance__program_99dbfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["program", "adult", "check_in"],
                name="attendance__program_b64c16_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfidcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("adult__isnull", True), ("student__isnull", False)),
                    models.Q(("adult__isnull", False), ("student__isnull", True)),
                    _connector="OR",
                ),
                name="rfid_card_owner_check",
            ),
        ),
    ]
