# Generated by Django 5.2.15 on 2026-07-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_attendanceevent_adult_attendancesession_adult_and_more"),
        ("programs", "0087_remove_adult_insert_insert_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                condition=models.Q(("check_out__isnull", True)),
                fields=["program", "student", "check_in"],
                name="att_sess_open_student_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                condition=models.Q(("check_out__isnull", True)),
                fields=["program", "adult", "check_in"],
                name="att_sess_open_adult_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["program", "visitor_name", "check_in"],
                name="att_sess_prog_visitor_in_idx",
            ),
        ),
    ]
