# Generated by Django 6.1 on 2026-08-29 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import attendance.models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendancesession_att_sess_open_student_idx_and_more"),
        ("programs", "0111_alter_adultevent_legal_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalSignoutConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name for this sign-out station (e.g. 'Front Door').",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive sign-out stations return a 404 page.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Program whose students can be signed out at this station.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signout_configs",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Sign-out Station",
                "verbose_name_plural": "Digital Sign-out Stations",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="DigitalSignout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signed_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Name the parent/guardian entered.",
                        max_length=200,
                    ),
                ),
                (
                    "signature",
                    models.FileField(
                        blank=True,
                        help_text="PNG image of the drawn signature.",
                        upload_to=attendance.models._signout_upload_to,
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_signouts",
                        to="programs.program",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="digital_signouts",
                        to="programs.student",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signouts",
                        to="attendance.digitalsignoutconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["program", "student", "signed_at"],
                        name="attendance__program_b09b6e_idx",
                    )
                ],
            },
        ),
    ]
