# Generated by Django 6.1 on 2026-09-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_studentpresence"),
        ("programs", "0115_alter_rolepermission_section"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendanceevent",
            name="attendance__program_686436_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendanceevent",
            name="attendance__program_99dbfa_idx",
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["student", "check_in"], name="attendance__student_2a9ce2_idx"
            ),
        ),
    ]
