# Generated by Django 6.1 on 2026-09-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0010_remove_attendanceevent_attendance__program_686436_idx_and_more",
        ),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this attendance event belongs to (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_events",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this attendance session belongs to (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_sessions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="digitalsignout",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this sign-out (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="digital_signouts",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="digitalsignoutconfig",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this sign-out station (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signout_configs",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="kioskconfig",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this kiosk config (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kiosk_configs",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="kioskdevice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this device (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kiosk_devices",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="rfidcard",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this card (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfid_cards",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="studentpresence",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this presence record (multi-tenant; null until backfilled).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_presences",
                to="organizations.organization",
            ),
        ),
    ]
