# Generated by Django 5.2.16 on 2026-08-24 19:22

import badges.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0107_remove_slidingscale_slidingscale_student_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=badges.models.badge_icon_upload_to)),
                ('category', models.CharField(choices=[('Basics', 'Basics'), ('Design', 'Design'), ('Software', 'Software'), ('Manufacturing', 'Manufacturing'), ('Data Science', 'Data Science'), ('Electrical', 'Electrical'), ('General', 'General')], default='General', max_length=30)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('skills_required', models.TextField(blank=True, help_text='Visible to students')),
                ('how_to_earn', models.TextField(blank=True, help_text='Only visible to mentors')),
                ('prerequisites', models.ManyToManyField(blank=True, to='badges.badge')),
            ],
            options={
                'ordering': ['category', 'name', 'level'],
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='badges.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='programs.student')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
